// Generated by tools/aura-kinds.mjs from src/sim/aura_classify.ts in world-of-claudecraft 0.34.0. Do not hand-edit.
//
// Every aura kind the game treats as harmful by nature, which is what
// `world.harmful` answers true for without consulting a magnitude. Regenerate
// with `pnpm aura-kinds` after a game release changes the set.
//
// Autocomplete only. Ask `world.harmful(aura)` rather than testing membership
// yourself: the game's rule has a second clause this union cannot carry, since a
// `buff_*` kind with a negative magnitude is a drain and is harmful too.
//
// OPEN, like every generated union here. The set is content, a game release adds
// to it before these types catch up, and a published type must never be able to
// break a working addon.

export type KnownHarmfulAuraKind =
  | 'attackspeed'
  | 'bleed_vuln'
  | 'blind'
  | 'cauterize_fatigue'
  | 'corrode'
  | 'cost_tax'
  | 'critvuln'
  | 'debuff_ap'
  | 'disarm'
  | 'dot'
  | 'expose'
  | 'faerie_fire'
  | 'heal_absorb'
  | 'hex'
  | 'incapacitate'
  | 'lockout'
  | 'mortal_wound'
  | 'polymorph'
  | 'root'
  | 'sated'
  | 'silence'
  | 'slow'
  | 'spellvuln'
  | 'stun'
  | 'sunder'
  | 'tongues'
  | 'vulnerability';

export type HarmfulAuraKind = KnownHarmfulAuraKind | (string & Record<never, never>);
