// Generated by tools/aura-kinds.mjs from src/sim/aura_classify.ts in world-of-claudecraft 0.43.3. Do not hand-edit.
//
// Every aura kind the game treats as harmful BY NATURE, whatever its magnitude.
// Regenerate with `pnpm aura-kinds` after a game release changes the set.
//
// This is half of the game's rule and not the whole of it. The other half is a
// sign test: a `buff_*` kind whose magnitude went negative is a drain and is
// harmful too, which is why a mob sapping attack power does not need its own
// kind. `world/auras.ts` is where the two clauses are put back together, and it
// is the only place that should: an addon that reads a set writes its own
// classifier, which is the drift the game's own one-classifier rule exists to
// prevent, one level out.
//
// A kind added by a release this file predates reads as NOT harmful. That is the
// conservative direction and the published contract says so: an effect nobody
// classified is not offered as something to remove.

const DEBUFF_AURA_KINDS: ReadonlySet<string> = new Set([
  'affliction_eye',
  'affliction_eye_secondary',
  'affliction_violence',
  'attackspeed',
  'bleed_vuln',
  'blind',
  'cauterize_fatigue',
  'cheater_mark',
  'corrode',
  'cost_tax',
  'critvuln',
  'debuff_ap',
  'disarm',
  'dot',
  'duskfire_claim',
  'expose',
  'faerie_fire',
  'forced_move',
  'heal_absorb',
  'hex',
  'incapacitate',
  'lockout',
  'melting_acid',
  'mortal_wound',
  'necromancy_harvest_mark',
  'polymorph',
  'root',
  'ruinous_brand',
  'sated',
  'silence',
  'slow',
  'spellvuln',
  'stun',
  'sun_verdict',
  'sunder',
  'tongues',
  'vuln_source',
  'vulnerability',
]);

// Every aura id `isDispellableAura` refuses OUTRIGHT, whatever the flags and the
// polarity on it say: one inline literal, and one set it consults for auras drawn
// on the debuff surface that are not removable effects.
//
// NOT published as a type, unlike the kinds above: an addon compares `aura.kind`
// and never has cause to name one of these.
const UNDISPELLABLE_AURA_IDS: ReadonlySet<string> = new Set([
  'divine_ascension',
  'shaman_stormsurge_ready',
]);

// The game's TOGGLE rule (`isToggleAura` in the same classifier, plus the
// engine-bank term it calls into `src/sim/persistent_aura.ts` for). An aura that
// answers this is a MODE, not a timed effect: the sim backs a stance, a form,
// stealth, Ghost Wolf, the carried flag and the rotation banks with a long
// finite duration (3600s, or a whole match) that is SCAFFOLDING rather than
// information, so no surface may print a countdown for one.
//
// UNLIKE the dispel rule above, this one is implemented WHOLE: it reads `kind`
// and `id` and `wireAura` sends both, so there is no clause a client cannot see.
//
// The two id sets the game declares are merged, because the predicate ORs them
// and nothing here can use the difference.
// The opening comment in each body is LOAD-BEARING and not decoration: the
// formatter collapses a short array onto one line and keeps an array carrying a
// comment expanded, so without it the layout of these three would depend on how
// many members the game happens to declare, and the round-trip that proves this
// file is what the generator writes would break the day a set got small enough.
const TOGGLE_AURA_KINDS: ReadonlySet<string> = new Set([
  // A mode whatever id rides it.
  'battle_stance',
  'berserker_stance',
  'defensive_stance',
  'form_bear',
  'form_cat',
  'form_fireball',
  'form_moonkin',
  'form_shadow',
  'form_travel',
  'stealth',
]);

const TOGGLE_AURA_IDS: ReadonlySet<string> = new Set([
  // A mode whatever kind it rides: the authored toggles and the engine banks.
  'beacon_of_light',
  'bg_carried_flag',
  'ghost_wolf',
  'hunter_efficient_rhythm_progress',
  'hunter_efficient_rhythm_ready',
  'hunter_fang_chorus_counter',
  'hunter_overdraw_counter',
  'moontide',
  'old_blood',
  'shaman_flow_state_progress',
  'shaman_flow_state_ready',
  'shaman_pyrebrand_mastery',
  'shaman_thunder_charges',
  'shaman_warspirit_cadence',
  'stampede_ready',
  'sunwake',
  'verdance',
]);

// The inverse override: an aura riding a toggle KIND that is a genuine timed
// buff and does want its countdown. Greater Invisibility reuses the rogue stealth
// machinery and is a fixed 20s buff.
const TIMED_AURA_IDS: ReadonlySet<string> = new Set([
  // Checked FIRST, so it wins over both sets above.
  'greater_invisibility',
]);

export {
  DEBUFF_AURA_KINDS,
  TIMED_AURA_IDS,
  TOGGLE_AURA_IDS,
  TOGGLE_AURA_KINDS,
  UNDISPELLABLE_AURA_IDS,
};
