// Generated by tools/aura-kinds.mjs from src/sim/aura_classify.ts in world-of-claudecraft 0.41.1. Do not hand-edit.
//
// Every aura kind the game treats as harmful BY NATURE, whatever its magnitude.
// Regenerate with `pnpm aura-kinds` after a game release changes the set.
//
// This is half of the game's rule and not the whole of it. The other half is a
// sign test: a `buff_*` kind whose magnitude went negative is a drain and is
// harmful too, which is why a mob sapping attack power does not need its own
// kind. `world/auras.ts` is where the two clauses are put back together, and it
// is the only place that should: an addon that reads a set writes its own
// classifier, which is the drift the game's own one-classifier rule exists to
// prevent, one level out.
//
// A kind added by a release this file predates reads as NOT harmful. That is the
// conservative direction and the published contract says so: an effect nobody
// classified is not offered as something to remove.

const DEBUFF_AURA_KINDS: ReadonlySet<string> = new Set([
  'affliction_eye',
  'affliction_eye_secondary',
  'affliction_violence',
  'attackspeed',
  'bleed_vuln',
  'blind',
  'cauterize_fatigue',
  'cheater_mark',
  'corrode',
  'cost_tax',
  'critvuln',
  'debuff_ap',
  'disarm',
  'dot',
  'duskfire_claim',
  'expose',
  'faerie_fire',
  'forced_move',
  'heal_absorb',
  'hex',
  'incapacitate',
  'lockout',
  'melting_acid',
  'mortal_wound',
  'necromancy_harvest_mark',
  'polymorph',
  'root',
  'ruinous_brand',
  'sated',
  'silence',
  'slow',
  'spellvuln',
  'stun',
  'sun_verdict',
  'sunder',
  'tongues',
  'vuln_source',
  'vulnerability',
]);

// Every aura id `isDispellableAura` refuses OUTRIGHT, whatever the flags and the
// polarity on it say: one inline literal, and one set it consults for auras drawn
// on the debuff surface that are not removable effects.
//
// NOT published as a type, unlike the kinds above: an addon compares `aura.kind`
// and never has cause to name one of these.
const UNDISPELLABLE_AURA_IDS: ReadonlySet<string> = new Set([
  'divine_ascension',
  'shaman_stormsurge_ready',
]);

export { DEBUFF_AURA_KINDS, UNDISPELLABLE_AURA_IDS };
