// The cue-name union: how it is derived, and that the checked-in file is what the generator
// would write. Staleness against the deployed game is checked by running `pnpm cues`.

import { describe, expect, it } from 'vitest';
// biome-ignore lint/correctness/noUnresolvedImports: Vite's ?raw suffix is a loader directive a static resolver does not model. Same reason as the addon suites.
import GENERATED_TEXT from '../packages/types/cues.generated.d.ts?raw';
import { cueNames, renderCueTypes } from '../tools/cues-core.ts';

/** A pack in the shape the game deploys: a cue can have several variants. */
function pack(clips: Record<string, unknown>): unknown {
  return { format: 'woc-sfx-runtime-pack', version: 1, clips };
}

function clip(): unknown {
  return { variants: [{ id: 'main', url: '/audio/sfx/x.mp3?v=1', bytes: 1 }], gain: 1, rate: 1 };
}

/** The cue names in the checked-in file, read back out of the union. */
function namesInFile(): string[] {
  return [...GENERATED_TEXT.matchAll(/^ {2}\| '([^']+)'/gm)].map((match) => match[1] ?? '');
}

/** The source URL the header records, which the generator writes into the file. */
function sourceInFile(): string {
  return /from (\S+)\./.exec(GENERATED_TEXT)?.[1] ?? '';
}

describe('reading a pack', () => {
  it('names every cue, sorted', () => {
    // Built rather than literal: cue names are the game's identifiers, not ours to lint.
    const clips = Object.fromEntries(
      ['ui_click', 'amb_rain', 'combat_block'].map((n) => [n, clip()]),
    );

    expect(cueNames(pack(clips))).toEqual(['amb_rain', 'combat_block', 'ui_click']);
  });

  // A directory listing would count variant files, most of which are not cue names.
  it('counts a multi-variant family as one cue', () => {
    const multi = { variants: [{ id: '1' }, { id: '2' }, { id: '3' }], gain: 1 };
    const clips = Object.fromEntries([['combat_block', multi]]);

    expect(cueNames(pack(clips))).toEqual(['combat_block']);
  });

  // Each would otherwise generate a file that compiles and silently loses autocomplete.
  it.each([
    ['not an object', 42],
    ['a payload with the wrong format tag', { format: 'something-else', clips: { a: {} } }],
    ['a pack with no clips', { format: 'woc-sfx-runtime-pack' }],
    ['a pack that names nothing', pack({})],
  ])('refuses %s', (_label, input) => {
    expect(() => cueNames(input)).toThrow();
  });
});

describe('rendering the union', () => {
  it('writes one member per cue', () => {
    const text = renderCueTypes(['amb_rain', 'ui_click'], 'https://example.test/pack.json');

    expect(text).toContain("  | 'amb_rain'\n  | 'ui_click';");
  });

  it('says where it came from and that it is generated', () => {
    const text = renderCueTypes(['ui_click'], 'https://example.test/pack.json');

    expect(text).toContain('Generated by tools/cues.mjs from https://example.test/pack.json');
    expect(text).toContain('Do not hand-edit');
  });
});

describe('the checked-in file', () => {
  it('carries the cues the deployed game had when it was generated', () => {
    expect(namesInFile().length).toBeGreaterThan(0);
  });

  it('records the host it was generated from', () => {
    expect(sourceInFile()).toContain('/audio/sfx/runtime-pack.json');
  });

  // Catches the header and layout only: names are read back out of this file, so a
  // hand-added name round-trips.
  it('is laid out exactly the way the generator writes it', () => {
    expect(GENERATED_TEXT).toBe(renderCueTypes(namesInFile(), sourceInFile()));
  });

  // Catches a hand-added name, which rarely lands in code-point order.
  it('is sorted and free of duplicates', () => {
    const names = namesInFile();

    expect(names).toEqual([...new Set(names)].sort());
  });
});
