// The README's generated addon section.
//
// There is deliberately NO test that the committed README matches a fresh
// render, and the first version of this file had one. It was the wrong model and
// it failed twice within a day, both times honestly: `marketplace.json` is
// generated by a bot on main and nothing asks a contributor to regenerate it
// before pushing, and the README section is generated by the same job in the
// same commit. A drift test turns that bot-owned file into a red build for every
// change that lands an addon, which is every change the bot exists to handle.
//
// What IS pinned here is everything that can go wrong without a person noticing:
// the render covering every addon, the author tools being named rather than
// silently dropped, the summariser's sentence rule, and the MARKERS still being
// in the file. The markers are the load-bearing one. `pnpm readme` treats a
// README without them as nothing to do, which is right for a third-party
// marketplace copying the workflow and silent for us: the sync would simply stop
// and the section would sit there going stale with nothing to say so.

import { describe, expect, it } from 'vitest';
import { isAuthorTool, readAddons } from '../tools/catalog.ts';
import {
  END,
  firstSentence,
  readReadme,
  renderAddons,
  START,
  spliceReadme,
} from '../tools/readme-core.ts';

describe('README.md', () => {
  it('still carries the markers the generator writes between', () => {
    // Dropping these is how the sync stops without failing: `pnpm readme` and the
    // workflow both treat their absence as "this README has no generated
    // section", so nothing would ever report it again.
    const readme = readReadme();
    expect(readme, `README.md has lost ${START}; the addon section will stop syncing`).toContain(
      START,
    );
    expect(readme).toContain(END);
    expect(readme.indexOf(START)).toBeLessThan(readme.indexOf(END));
  });

  it('lists every addon a player installs, and links each to its directory', () => {
    const rendered = renderAddons(readAddons());
    for (const addon of readAddons()) {
      expect(rendered, `${addon.id} is missing from the README`).toContain(
        `[${addon.name}](addons/${addon.id})`,
      );
    }
  });

  it('counts what it lists, rather than a number somebody typed', () => {
    // The count in that sentence is the catalog's own length. This test asserted
    // a literal 31 once, which passed on the machine it was written on and failed
    // in CI against a repository holding a different number of addons.
    const all = readAddons();
    const listed = all.filter((one) => !isAuthorTool(one)).length;
    expect(renderAddons(all)).toContain(`**${listed} addons ship with the loader**`);
  });

  it('names the author tools it left out rather than shortening the count', () => {
    const all = readAddons();
    const tools = all.filter((one) => isAuthorTool(one));
    const rendered = renderAddons(all);
    for (const tool of tools) {
      // Dev Harness ships and is in the in-game Browse. A README whose count is
      // one short of what the game offers is the report this prevents.
      expect(rendered).toContain(`[${tool.name}](addons/${tool.id})`);
    }
  });

  it('refuses to write into a file that has lost its markers', () => {
    expect(() => spliceReadme('# nothing here\n', 'x')).toThrow(/markers/);
  });
});

describe('the summary one line each is cut to', () => {
  it('stops at the first sentence', () => {
    expect(firstSentence('A bar per cooldown. Sorted soonest first.')).toBe('A bar per cooldown.');
  });

  it('keeps a description that is one sentence whole', () => {
    const one = 'What your damage is made of: a row per ability, worst first.';
    expect(firstSentence(one)).toBe(one);
  });

  it('does not cut at a full stop that is not the end of a sentence', () => {
    // Only a capital starts the next sentence, so `4.4s`, `woc.ui.frame` and an
    // abbreviation mid-clause all stay put. A length-based cut would take the
    // first of these mid-number.
    expect(firstSentence('A bar reading 4.4s, e.g. a cooldown.')).toBe(
      'A bar reading 4.4s, e.g. a cooldown.',
    );
  });
});
