// Filtering auras, on an entity and on a party row. "Is MY dot on this target" needs
// `sourceId`: two players can apply the same debuff.
//
// A party row's aura is a much smaller shape (id, kind, whole-second remaining, `neg`; no source,
// stacks or duration), so its query is deliberately narrower rather than ignoring `mine`.

import {
  DEBUFF_AURA_KINDS,
  TIMED_AURA_IDS,
  TOGGLE_AURA_IDS,
  TOGGLE_AURA_KINDS,
  UNDISPELLABLE_AURA_IDS,
} from '../../shared/aura-kinds.generated.ts';
import type { Aura } from './game-types.ts';
import type { PartyMemberAura } from './party-types.ts';

interface AuraQuery {
  /** The applying ability's id. */
  id?: string;
  /** What the effect does, e.g. 'dot' or 'stun'. */
  kind?: string;
  /** Only effects the player applied. Needs a player id to mean anything. */
  mine?: boolean;
  /** True for harmful effects only, false for beneficial only, absent for both. */
  harmful?: boolean;
}

interface PartyAuraQuery {
  id?: string;
  kind?: string;
  /**
   * True for debuffs only, false for buffs only, absent for both. Runs the game's classification:
   * the row's `neg` flag alone is a sign test that a dot or a root never sets.
   */
  debuff?: boolean;
}

/** The prefix the game reuses for a stat aura, whichever direction it points. */
const BUFF_PREFIX = 'buff_';
/** The one school no dispel reaches, in either direction. */
const PHYSICAL = 'physical';

const NONE: readonly Aura[] = Object.freeze([]);
const NO_ROWS: readonly PartyMemberAura[] = Object.freeze([]);

/**
 * Whether an effect works AGAINST the unit carrying it.
 *
 * A predicate, not a field: addons get the game's own aura objects, so a field would mean
 * mutating game state or copying every aura per frame.
 *
 * The game's rule has two clauses: a kind in the harmful set, or a `buff_*` kind with a negative
 * magnitude (a drain reusing the buff kind, which the set does not list). It takes either
 * shape: a party row's `neg` is set from the same sign. `value` must stay RAW; rounding or
 * taking a magnitude reclassifies every drain as a benefit.
 */
function isHarmful(aura: Pick<Aura, 'kind'> & { value?: number; neg?: 1 }): boolean {
  if (DEBUFF_AURA_KINDS.has(aura.kind)) {
    return true;
  }
  if (!aura.kind.startsWith(BUFF_PREFIX)) {
    return false;
  }
  return aura.neg === 1 || (aura.value ?? 0) < 0;
}

/**
 * Whether an effect can be removed, and in which direction.
 *
 * Six of the game's seven clauses (`isDispellableAura` and `isPlayerRemovableAura` in
 * `src/sim/aura_classify.ts`): not a refused id, not permanent, not unbreakable control, not
 * undispellable, not physical, and the polarity asked for. `offensive` strips a BENEFIT off an
 * enemy; otherwise a harmful effect off an ally. `UNDISPELLABLE_AURA_IDS` is generated by
 * `pnpm aura-kinds`.
 *
 * The missing clause is `encounterOwned`, which `wireAura` never sends, so this answers TRUE for
 * raid mechanics the game refuses, including debuffs on players. On a game release, diff the
 * game's whole function against this one: a too-generous predicate never fails a test.
 *
 * Takes the FULL aura only: a party row has no school or flags, so it is refused.
 */
function isDispellable(aura: Aura, offensive: boolean): boolean {
  if (UNDISPELLABLE_AURA_IDS.has(aura.id)) {
    return false;
  }
  if (aura.permanent === true || aura.undispellable === true) {
    return false;
  }
  if (aura.unbreakableControl === true || aura.school === PHYSICAL) {
    return false;
  }
  const harmful = isHarmful(aura);
  if (offensive) {
    return !harmful;
  }
  return harmful;
}

/**
 * Whether an effect is a MODE rather than a timed one, so its clock means nothing.
 *
 * The game's whole `isToggleAura` (`src/sim/aura_classify.ts`). Stances, forms, stealth, Ghost
 * Wolf, Beacon of Light, the carried flag and the rotation banks carry a long placeholder
 * duration (an hour, or a whole match) that `remaining` counts down through, which is not
 * information. The sets are generated by `pnpm aura-kinds`. Takes either aura shape, since it
 * reads only `id` and `kind`.
 *
 * Check the timed override first: Greater Invisibility rides the `stealth` kind and is a real
 * 20s buff.
 */
function isToggle(aura: Pick<Aura, 'id' | 'kind'>): boolean {
  if (TIMED_AURA_IDS.has(aura.id)) {
    return false;
  }
  return TOGGLE_AURA_KINDS.has(aura.kind) || TOGGLE_AURA_IDS.has(aura.id);
}

function matches(aura: Aura, query: AuraQuery, playerId: number | null): boolean {
  if (query.id !== undefined && aura.id !== query.id) {
    return false;
  }
  if (query.kind !== undefined && aura.kind !== query.kind) {
    return false;
  }
  // A null player id matches nothing as "mine", or every aura is the player's before world entry.
  if (query.mine === true && (playerId === null || aura.sourceId !== playerId)) {
    return false;
  }
  if (query.harmful !== undefined && query.harmful !== isHarmful(aura)) {
    return false;
  }
  return true;
}

function rowMatches(aura: PartyMemberAura, query: PartyAuraQuery): boolean {
  if (query.id !== undefined && aura.id !== query.id) {
    return false;
  }
  if (query.kind !== undefined && aura.kind !== query.kind) {
    return false;
  }
  if (query.debuff !== undefined && query.debuff !== isHarmful(aura)) {
    return false;
  }
  return true;
}

/**
/** The effects on an entity that match, in the game's order. An empty query returns all. */
function filterAuras(
  auras: readonly Aura[] | null,
  query: AuraQuery,
  playerId: number | null,
): readonly Aura[] {
  if (auras === null) {
    return NONE;
  }
  return auras.filter((aura) => matches(aura, query, playerId));
}

/** The same over a party row's compact strip, which carries no source at all. */
function filterPartyAuras(
  auras: readonly PartyMemberAura[] | undefined,
  query: PartyAuraQuery,
): readonly PartyMemberAura[] {
  if (auras === undefined) {
    return NO_ROWS;
  }
  return auras.filter((aura) => rowMatches(aura, query));
}

export type { AuraQuery, PartyAuraQuery };
export { filterAuras, filterPartyAuras, isDispellable, isHarmful, isToggle, NO_ROWS, NONE };
