// Regenerate `addons/emberwatch/rules.json` from a game checkout.
//
//   node addons/emberwatch/generate.mjs --game=/path/to/world-of-claudecraft
//
// `--game /path` works too. Never hand-edit `rules.json`: `RULES` below is the source, and an
// edit made in the JSON is lost on the next run.
//
// DERIVED from the checkout: the stamped game version, every rule's display name, the class of an
// ability-anchored rule (a hard failure if it disagrees with the editorial class), and the class
// order. EDITORIAL, in `RULES`: which rules exist, their ids, unit, condition, threshold, cue,
// banner and bout flags, `mine`, and the label suffix ("fading", "ending", "gone"). The
// class-agnostic rules match on an aura kind and are editorial end to end.
//
// It reads, read-only:
//
//   src/sim/content/classes.ts        CLASSES for the class order, ABILITIES for
//                                     every id, its display name and its class.
//   src/sim/combat/auto_attack.ts     the proc auras that no ability table lists,
//   src/sim/combat/convergence.ts     applied straight through `ctx.applyAura` with
//   src/sim/combat/fire_mage.ts       a literal id and name.
//   src/sim/combat/frost_mage.ts
//   src/sim/combat/*.ts               every `kind: '...'` literal, as the vocabulary
//                                     a kind-anchored rule is checked against.
//   src/sim/encounters/ignivar.ts     every encounter aura the two raid bosses
//   src/sim/encounters/varkhul.ts     actually APPLY, plus the id, name and
//   src/sim/varkhul_intercept_beam.ts threshold constants those applications name.
//   src/sim/varkhul_shared_pyre.ts
//   package.json                      the version stamped into the output.
//
// An encounter rule is anchored on the APPLICATION, never on the constant: a constant can
// outlive its mechanic, so a rule naming an id nothing applies is a hard failure.
//
// Every release breakage below throws and writes nothing, because a rule that silently drops out
// is a rule that can never fire with nothing on screen to say so:
//
//  - an ability id disappears or is renamed, so the rule fails to resolve;
//  - an ability moves class, so the derived class stops matching the editorial one;
//  - an aura kind is renamed, so a kind-anchored rule stops matching the vocabulary;
//  - an encounter aura constant goes, or stops being applied (separate throws);
//  - a `thresholdConst` the game owns is no longer declared as a number;
//  - the source stops being parseable: these are regexes anchored on the game's exact
//    indentation, so a formatter change fails every id at once.
//
// A display name change is not a failure: the new name lands in the output and shows in the
// diff. `--game` is required because nothing 404s when a checkout is stale. The output is
// byte-stable (no timestamp, fixed key order, sorted by class order then id), so any diff means
// content moved.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

/** A trailing slash on --game, so a joined path never doubles it. */
const TRAILING_SLASH = /\/$/;
const GAME_FLAG = /^--game=(.+)$/;

/** The one file this may write, resolved against this script rather than the cwd. */
const OUTPUT = fileURLToPath(new URL('rules.json', import.meta.url));

const CLASSES_SOURCE = 'src/sim/content/classes.ts';
const COMBAT_DIR = 'src/sim/combat';
/**
 * Where a proc aura is applied without an ability table entry to name it. Listed, because a walk
 * of every `applyAura` would pick up encounter auras and depend on directory order.
 */
const PROC_SOURCES = [
  'src/sim/combat/auto_attack.ts',
  'src/sim/combat/convergence.ts',
  'src/sim/combat/fire_mage.ts',
  'src/sim/combat/frost_mage.ts',
];

/** Where a raid boss applies its own auras. Listed: a new encounter needs rules written anyway. */
const ENCOUNTER_SOURCES = ['src/sim/encounters/ignivar.ts', 'src/sim/encounters/varkhul.ts'];

/**
 * Where the constants those applications name are DECLARED. A superset of ENCOUNTER_SOURCES:
 * Varkhul imports its pyre and beam constants from the two pure modules beside it.
 */
const ENCOUNTER_CONST_SOURCES = [
  ...ENCOUNTER_SOURCES,
  'src/sim/varkhul_intercept_beam.ts',
  'src/sim/varkhul_shared_pyre.ts',
];

/** The game's package name, which proves a directory is the checkout. */
const GAME_PACKAGE = 'world-of-claudecraft';

const FORMAT = 'emberwatch-rules';
const FILE_VERSION = 1;
const INDENT = 2;
const NOTE =
  'Generated by addons/emberwatch/generate.mjs from a game checkout. Do not hand-edit: ' +
  'the editorial half lives in that script and a change made here is lost on the next run. ' +
  'Every id is the id an aura actually carries on the wire, which for a self-buff and a dot ' +
  "is the applying ability's id and for a raid mechanic is the encounter's own aura id.";

/** The class token a rule uses when it applies to every class. */
const ANY = 'any';
/** Rules for every class sort ahead of every real class, whatever the game's order. */
const ANY_RANK = -1;

/** Redhand banks two charges, so one is an opener and two is the thing to spend. */
const OVERPOWER_CHARGES = 2;
/** Three applications of anything harmful is the point a ramp is worth interrupting. */
const RAMPING_STACKS = 3;
/**
 * Ignivar's Molten Armor swap point is EDITORIAL: the game declares no constant for it, so it
 * will not follow a game change. Replace it with a `thresholdConst` if Ignivar gains one.
 */
const MOLTEN_ARMOR_SWAP_STACKS = 2;

/**
 * The editorial set: everything a checkout cannot decide.
 *
 * `ability` names the id whose display name becomes the label and whose existence is checked;
 * `suffix` is the editorial half of the label. A rule with no `ability` matches on a kind or on
 * polarity alone and carries its own `label`.
 */
const RULES = [
  {
    id: 'stunned',
    cls: ANY,
    unit: 'player',
    kind: 'stun',
    on: 'gained',
    cue: 'ui_error',
    banner: true,
    label: 'Stunned',
  },
  {
    id: 'silenced',
    cls: ANY,
    unit: 'player',
    kind: 'silence',
    on: 'gained',
    cue: 'ui_error',
    label: 'Silenced',
  },
  {
    id: 'stacking-on-you',
    cls: ANY,
    unit: 'player',
    harmful: true,
    on: 'stacks',
    threshold: RAMPING_STACKS,
    cue: 'debuff_apply',
    label: 'Stacking up on you',
  },
  {
    id: 'bout-target-untouchable',
    cls: ANY,
    unit: 'target',
    kind: 'stasis',
    on: 'gained',
    cue: 'ui_error',
    bout: true,
    label: 'Target untouchable',
  },

  {
    id: 'warrior-battle-trance',
    cls: 'warrior',
    unit: 'player',
    ability: 'battle_trance',
    on: 'gained',
    cue: 'buff_apply',
  },
  {
    id: 'warrior-sudden-death',
    cls: 'warrior',
    unit: 'player',
    ability: 'sudden_death',
    on: 'gained',
    cue: 'buff_apply',
  },
  {
    id: 'warrior-overpower',
    cls: 'warrior',
    unit: 'player',
    ability: 'overpower',
    on: 'stacks',
    threshold: OVERPOWER_CHARGES,
    suffix: 'at two',
  },
  {
    id: 'warrior-recklessness',
    cls: 'warrior',
    unit: 'player',
    ability: 'recklessness',
    on: 'expiring',
    suffix: 'ending',
  },

  {
    id: 'mage-hot-streak',
    cls: 'mage',
    unit: 'player',
    ability: 'hot_streak',
    on: 'gained',
    cue: 'buff_apply',
  },
  {
    id: 'mage-brain-freeze',
    cls: 'mage',
    unit: 'player',
    ability: 'brain_freeze',
    on: 'gained',
    cue: 'buff_apply',
  },
  {
    id: 'mage-arcane-power',
    cls: 'mage',
    unit: 'player',
    ability: 'arcane_power',
    on: 'expiring',
    suffix: 'ending',
  },
  {
    id: 'mage-pyroblast',
    cls: 'mage',
    unit: 'target',
    ability: 'pyroblast',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },

  {
    id: 'rogue-cold-blood',
    cls: 'rogue',
    unit: 'player',
    ability: 'cold_blood',
    on: 'gained',
    cue: 'buff_apply',
  },
  {
    id: 'rogue-rupture',
    cls: 'rogue',
    unit: 'target',
    ability: 'rupture',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'rogue-garrote',
    cls: 'rogue',
    unit: 'target',
    ability: 'garrote',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'rogue-evasion',
    cls: 'rogue',
    unit: 'player',
    ability: 'evasion',
    on: 'expiring',
    suffix: 'ending',
  },

  {
    id: 'paladin-sacred-bulwark',
    cls: 'paladin',
    unit: 'player',
    ability: 'sacred_bulwark',
    on: 'expiring',
    suffix: 'ending',
  },
  {
    id: 'paladin-righteous-fury',
    cls: 'paladin',
    unit: 'player',
    ability: 'righteous_fury',
    on: 'faded',
    cue: 'ui_error',
    suffix: 'gone',
  },

  {
    id: 'hunter-serpent-sting',
    cls: 'hunter',
    unit: 'target',
    ability: 'serpent_sting',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'hunter-bestial-wrath',
    cls: 'hunter',
    unit: 'player',
    ability: 'bestial_wrath',
    on: 'expiring',
    suffix: 'ending',
  },
  {
    id: 'hunter-rapid-fire',
    cls: 'hunter',
    unit: 'player',
    ability: 'rapid_fire',
    on: 'expiring',
    suffix: 'ending',
  },

  {
    id: 'priest-shadow-word-pain',
    cls: 'priest',
    unit: 'target',
    ability: 'shadow_word_pain',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'priest-shadowform',
    cls: 'priest',
    unit: 'player',
    ability: 'shadowform',
    on: 'faded',
    suffix: 'gone',
  },

  {
    id: 'shaman-flame-shock',
    cls: 'shaman',
    unit: 'target',
    ability: 'flame_shock',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'shaman-convergence',
    cls: 'shaman',
    unit: 'player',
    ability: 'elemental_convergence',
    on: 'gained',
    cue: 'buff_apply',
  },
  {
    id: 'shaman-elemental-mastery',
    cls: 'shaman',
    unit: 'player',
    ability: 'elemental_mastery',
    on: 'gained',
    cue: 'buff_apply',
  },

  {
    id: 'warlock-corruption',
    cls: 'warlock',
    unit: 'target',
    ability: 'corruption',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'warlock-immolate',
    cls: 'warlock',
    unit: 'target',
    ability: 'immolate',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'warlock-curse-of-agony',
    cls: 'warlock',
    unit: 'target',
    ability: 'curse_of_agony',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'warlock-metamorphosis',
    cls: 'warlock',
    unit: 'player',
    ability: 'metamorphosis',
    on: 'expiring',
    suffix: 'ending',
  },

  {
    id: 'druid-moonfire',
    cls: 'druid',
    unit: 'target',
    ability: 'moonfire',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'druid-rip',
    cls: 'druid',
    unit: 'target',
    ability: 'rip',
    mine: true,
    on: 'expiring',
    suffix: 'fading',
  },
  {
    id: 'druid-tigers-fury',
    cls: 'druid',
    unit: 'player',
    ability: 'tigers_fury',
    on: 'expiring',
    suffix: 'ending',
  },
  {
    id: 'druid-barkskin',
    cls: 'druid',
    unit: 'player',
    ability: 'barkskin',
    on: 'expiring',
    suffix: 'ending',
  },

  // Ignivar. No `bout` on any raid rule: `world.match` is null in a raid, so a bout clause would
  // switch the rule off.
  {
    // `gained` rather than a stack threshold: the brand asks you to move away at one stack,
    // and the generic `stacking-on-you` rule already covers the ramp reaching three.
    id: 'raid-ignivar-brand',
    cls: ANY,
    unit: 'player',
    auraConst: 'IGNIVAR_BRAND_AURA_ID',
    on: 'gained',
    cue: 'debuff_apply',
    banner: true,
  },
  {
    // The tank swap: the threshold is where the swap is due, not the cap.
    id: 'raid-ignivar-molten-armor',
    cls: ANY,
    unit: 'player',
    auraConst: 'IGNIVAR_MOLTEN_ARMOR_AURA_ID',
    on: 'stacks',
    threshold: MOLTEN_ARMOR_SWAP_STACKS,
    cue: 'ui_error',
    banner: true,
  },
  {
    // On the BOSS, so it needs the boss selected.
    id: 'raid-ignivar-last-inferno',
    cls: ANY,
    unit: 'target',
    auraConst: 'IGNIVAR_LAST_INFERNO_AURA_ID',
    on: 'gained',
    cue: 'ui_error',
    banner: true,
  },

  // Varkhul.
  {
    // Like Molten Armor, but the game declares the swap point.
    id: 'raid-varkhul-makers-brand',
    cls: ANY,
    unit: 'player',
    auraConst: 'VARKHUL_MAKERS_BRAND_AURA_ID',
    on: 'stacks',
    thresholdConst: 'VARKHUL_MAKERS_BRAND_TANK_SWAP_STACKS',
    cue: 'ui_error',
    banner: true,
  },
  {
    // No banner: it asks nothing of you, only of whoever is healing you.
    id: 'raid-varkhul-tempered-wound',
    cls: ANY,
    unit: 'player',
    auraConst: 'VARKHUL_INTERCEPT_BEAM_DEBUFF_AURA_ID',
    on: 'gained',
    cue: 'debuff_apply',
  },
  {
    // The soak: `stacks` is bodies required, not applications. See `counts` in main.js.
    id: 'raid-varkhul-shared-pyre',
    cls: ANY,
    unit: 'player',
    auraConst: 'VARKHUL_SHARED_PYRE_AURA_ID',
    on: 'gained',
    counts: 'soakers',
    cue: 'ui_error',
    banner: true,
  },
  {
    id: 'raid-varkhul-cinder-orbs',
    cls: ANY,
    unit: 'player',
    auraConst: 'VARKHUL_CINDER_ORBS_AURA_ID',
    on: 'gained',
    cue: 'debuff_apply',
    banner: true,
  },
  {
    // The mark lands with a dot AND a heal absorb. Only the absorb is watched: health bars
    // already show the dot, and nothing on screen explains healing that stops landing.
    id: 'raid-varkhul-red-hot-metal',
    cls: ANY,
    unit: 'player',
    auraConst: 'VARKHUL_RED_HOT_METAL_ABSORB_AURA_ID',
    on: 'gained',
    cue: 'debuff_apply',
  },
];

/** A top-level entry in the CLASSES or ABILITIES record: exactly two spaces in. */
const RECORD_ENTRY_RE = /^ {2}([a-z0-9_]+): \{$/gm;
/** A property of one of those entries: exactly four. Both quote styles, since an apostrophe in a
 *  name ("Killer's Calm") forces double quotes. */
const NAME_RE = /^ {4}name: (?:'([^']*)'|"([^"]*)")/m;
const CLASS_RE = /^ {4}class: '([a-z]+)'/m;
/** One `ctx.applyAura(target, { ... })` call with literal fields. */
const APPLY_AURA_RE = /applyAura\([^)]*?\{([\s\S]{0,400}?)\}\s*\)/g;
const AURA_ID_RE = /\bid: '([a-z0-9_]+)'/;
const AURA_NAME_RE = /\bname: (?:'([^']*)'|"([^"]*)")/;
const KIND_RE = /\bkind: '([a-z0-9_]+)'/g;
/**
 * One top-level `const NAME = <literal>;`, exported or not. Anchored at column zero so an
 * object field cannot match, and deliberately not an alias (`const A = B;`).
 */
const CONST_DECL_RE =
  /^(?:export )?const ([A-Z][A-Z0-9_]*) = (?:'([^']*)'|"([^"]*)"|(-?\d+(?:\.\d+)?));$/gm;
/** The `id:` and `name:` fields of an `applyAura` object, as a literal or an identifier. */
const APPLY_ID_RE = /^ +id: (?:'([^']*)'|"([^"]*)"|([A-Za-z_][A-Za-z0-9_]*)),$/m;
const APPLY_NAME_RE = /^ +name: (?:'([^']*)'|"([^"]*)"|([A-Za-z_][A-Za-z0-9_]*)),$/m;
/** What an `applyAura` call opens with, matched as text so the object can be brace-scanned. */
const APPLY_AURA_CALL = 'applyAura(';

function reason(err) {
  if (err instanceof Error) {
    return err.message;
  }
  return String(err);
}

/**
 * The checkout root, from `--game=X` or `--game X`. Never defaulted: a default would silently read
 * whatever checkout happened to be at that path.
 */
function gameArg() {
  const inline = process.argv.map((value) => GAME_FLAG.exec(value)).find((match) => match !== null);
  if (inline !== undefined) {
    return inline[1].replace(TRAILING_SLASH, '');
  }
  const at = process.argv.indexOf('--game');
  if (at === -1) {
    throw new Error(
      '--game is required and has no default: this reads a CHECKOUT rather than an ' +
        'endpoint, so nothing will 404 to tell you it is stale. Pass the game repository ' +
        'root, e.g. --game=/path/to/world-of-claudecraft',
    );
  }
  const given = process.argv[at + 1];
  if (given === undefined) {
    throw new Error('--game needs a value, e.g. --game=/path/to/world-of-claudecraft');
  }
  return given.replace(TRAILING_SLASH, '');
}

function read(path) {
  try {
    return readFileSync(path, 'utf8');
  } catch (err) {
    throw new Error(`${path} could not be read: ${reason(err)}`, { cause: err });
  }
}

/** The checkout's version, after checking the package name proves this is the game checkout. */
function gameVersion(checkout) {
  const parsed = JSON.parse(read(`${checkout}/package.json`));
  if (parsed?.name !== GAME_PACKAGE) {
    throw new Error(
      `${checkout} is not the game checkout: its package.json is named ` +
        `"${String(parsed?.name)}" rather than "${GAME_PACKAGE}"`,
    );
  }
  const version = parsed?.version;
  if (typeof version !== 'string' || version.length === 0) {
    throw new Error(`${checkout}/package.json declares no version`);
  }
  return version;
}

/** Every top-level entry of a record, as `[key, body]`, in source order. */
function entriesOf(source) {
  const marks = [...source.matchAll(RECORD_ENTRY_RE)].map((match) => ({
    key: match[1],
    at: match.index,
  }));
  return marks.map((mark, at) => [mark.key, source.slice(mark.at, marks[at + 1]?.at)]);
}

/** The slice of a file between two `export const` markers. */
function section(source, from, to) {
  const start = source.indexOf(from);
  if (start === -1) {
    throw new Error(`${CLASSES_SOURCE} no longer declares ${from}`);
  }
  const end = source.indexOf(to, start);
  if (end === -1) {
    throw new Error(`${CLASSES_SOURCE} no longer declares ${to}`);
  }
  return source.slice(start, end);
}

/** The game's class order, which the output groups rules by. Derived, so a release reorders it. */
function classOrder(source) {
  const found = entriesOf(section(source, 'export const CLASSES', 'export const ABILITIES')).map(
    ([key]) => key,
  );
  if (found.length === 0) {
    throw new Error(`${CLASSES_SOURCE}: no classes found, so the table format has moved`);
  }
  return found;
}

/** Ability id to its display name and the class it belongs to. */
function abilities(source) {
  const found = new Map();
  for (const [key, body] of entriesOf(source.slice(source.indexOf('export const ABILITIES')))) {
    const name = NAME_RE.exec(body);
    const cls = CLASS_RE.exec(body);
    if (name !== null) {
      found.set(key, { name: name[1] ?? name[2], cls: cls?.[1] ?? null });
    }
  }
  if (found.size === 0) {
    throw new Error(`${CLASSES_SOURCE}: no abilities found, so the table format has moved`);
  }
  return found;
}

/**
 * The proc auras applied straight through `applyAura` with no ability entry. A name collision
 * between two files throws, since first-wins would depend on list order.
 */
function procAuras(checkout) {
  const found = new Map();
  for (const relative of PROC_SOURCES) {
    for (const [, body] of read(`${checkout}/${relative}`).matchAll(APPLY_AURA_RE)) {
      const id = AURA_ID_RE.exec(body);
      const name = AURA_NAME_RE.exec(body);
      if (id !== null && name !== null) {
        addAura(found, id[1], name[1] ?? name[2], relative);
      }
    }
  }
  return found;
}

function addAura(found, id, name, relative) {
  const seen = found.get(id);
  if (seen !== undefined && seen.name !== name) {
    throw new Error(
      `aura "${id}" is named "${seen.name}" in ${seen.from} and "${name}" in ${relative}`,
    );
  }
  found.set(id, { name, from: relative });
}

/** The index of the `}` closing the `{` at `open`, or -1 when the source ran out. */
function matchingBrace(source, open) {
  let depth = 0;
  for (let at = open; at < source.length; at += 1) {
    if (source[at] === '{') {
      depth += 1;
    }
    if (source[at] === '}') {
      depth -= 1;
      if (depth === 0) {
        return at;
      }
    }
  }
  return -1;
}

/**
 * Every `applyAura(target, { ... })` object body in a source. Brace-matched, because an encounter
 * literal is long and nested and a length-capped regex silently matches none of it.
 */
function applyAuraBodies(source) {
  const bodies = [];
  let at = source.indexOf(APPLY_AURA_CALL);
  while (at !== -1) {
    const open = source.indexOf('{', at);
    const close = matchingBrace(source, open);
    if (open !== -1 && close !== -1) {
      bodies.push(source.slice(open + 1, close));
    }
    at = source.indexOf(APPLY_AURA_CALL, at + APPLY_AURA_CALL.length);
  }
  return bodies;
}

/** A literal field, or an identifier resolved against the checkout's own constants. */
function applyField(body, pattern, consts) {
  const match = pattern.exec(body);
  if (match === null) {
    return null;
  }
  const literal = match[1] ?? match[2];
  if (literal !== undefined) {
    return literal;
  }
  const named = consts.get(match[3])?.value;
  if (typeof named === 'string') {
    return named;
  }
  return null;
}

function constValue(match) {
  const literal = match[2] ?? match[3];
  if (literal !== undefined) {
    return literal;
  }
  return Number(match[4]);
}

/**
 * Every top-level constant the encounter sources declare, by name. Two values under one name
 * is a failure rather than last-wins, which would depend on the order of the source list.
 */
function constTable(checkout) {
  const found = new Map();
  for (const relative of ENCOUNTER_CONST_SOURCES) {
    for (const match of read(`${checkout}/${relative}`).matchAll(CONST_DECL_RE)) {
      addConst(found, match[1], constValue(match), relative);
    }
  }
  if (found.size === 0) {
    throw new Error('no encounter constants found, so the source format has moved');
  }
  return found;
}

function addConst(found, name, value, relative) {
  const seen = found.get(name);
  if (seen !== undefined && seen.value !== value) {
    throw new Error(
      `${name} is ${JSON.stringify(seen.value)} in ${seen.from} and ` +
        `${JSON.stringify(value)} in ${relative}`,
    );
  }
  found.set(name, { value, from: relative });
}

/** Every encounter aura the game APPLIES, keyed by wire id. Never built from the id constants. */
function encounterAuras(checkout, consts) {
  const found = new Map();
  for (const relative of ENCOUNTER_SOURCES) {
    for (const body of applyAuraBodies(read(`${checkout}/${relative}`))) {
      const id = applyField(body, APPLY_ID_RE, consts);
      const name = applyField(body, APPLY_NAME_RE, consts);
      if (id !== null && name !== null) {
        addAura(found, id, name, relative);
      }
    }
  }
  if (found.size === 0) {
    throw new Error(`${ENCOUNTER_SOURCES[0]}: no applied auras found, so the format has moved`);
  }
  return found;
}

/** Every aura kind literal the sim's combat code mentions, as a membership test. */
function auraKinds(checkout, classesSource) {
  const found = new Set();
  const files = readdirSync(`${checkout}/${COMBAT_DIR}`)
    .filter((name) => name.endsWith('.ts'))
    .sort();
  const sources = [
    classesSource,
    ...files.map((name) => read(`${checkout}/${COMBAT_DIR}/${name}`)),
  ];
  for (const source of sources) {
    for (const [, kind] of source.matchAll(KIND_RE)) {
      found.add(kind);
    }
  }
  if (found.size === 0) {
    throw new Error(`${COMBAT_DIR}: no aura kinds found, so the source format has moved`);
  }
  return found;
}

/** The display name a rule's label is built from, checked against the checkout. */
function nameFor(rule, sources) {
  const known = sources.table.get(rule.ability);
  if (known !== undefined) {
    if (known.cls !== null && known.cls !== rule.cls) {
      throw new Error(
        `rule "${rule.id}" is filed under ${rule.cls} and "${rule.ability}" is a ` +
          `${known.cls} ability`,
      );
    }
    return known.name;
  }
  const proc = sources.procs.get(rule.ability);
  if (proc !== undefined) {
    return proc.name;
  }
  throw new Error(
    `rule "${rule.id}" names "${rule.ability}", which is in neither the ability table ` +
      'nor any proc site this script reads',
  );
}

/** A threshold the GAME states, so a release moving the swap point moves the rule. */
function thresholdFor(rule, consts) {
  const value = consts.get(rule.thresholdConst)?.value;
  if (typeof value !== 'number') {
    throw new Error(
      `rule "${rule.id}" takes its threshold from ${rule.thresholdConst}, which no encounter ` +
        'source declares as a number',
    );
  }
  return value;
}

/** The label, aura id and derived threshold of a rule anchored on an encounter aura. */
function raidSubjectOf(rule, sources) {
  const auraId = sources.consts.get(rule.auraConst)?.value;
  if (typeof auraId !== 'string') {
    throw new Error(
      `rule "${rule.id}" names ${rule.auraConst}, which no encounter source declares as an id`,
    );
  }
  const applied = sources.applied.get(auraId);
  if (applied === undefined) {
    throw new Error(
      `rule "${rule.id}" names ${rule.auraConst} ("${auraId}"), which is declared and applied ` +
        'nowhere, so a rule on it could never fire',
    );
  }
  const subject = { label: labelFor(rule, applied.name), auraId };
  if (rule.thresholdConst !== undefined) {
    subject.threshold = thresholdFor(rule, sources.consts);
  }
  return subject;
}

function labelFor(rule, name) {
  if (rule.suffix === undefined) {
    return name;
  }
  return `${name} ${rule.suffix}`;
}

/** The label and the aura id half of a rule, derived or editorial. */
function subjectOf(rule, sources) {
  if (rule.auraConst !== undefined) {
    return raidSubjectOf(rule, sources);
  }
  if (rule.ability === undefined) {
    if (rule.kind !== undefined && !sources.kinds.has(rule.kind)) {
      throw new Error(`rule "${rule.id}" matches on kind "${rule.kind}", which the game has not`);
    }
    return { label: rule.label };
  }
  return { label: labelFor(rule, nameFor(rule, sources)), auraId: rule.ability };
}

/**
 * One output row, keys in a fixed order. An absent clause must be an absent KEY: the addon reads a
 * null clause as asked-for, and it would match nothing.
 */
function rowFor(rule, subject) {
  const row = { id: rule.id, class: rule.cls, label: subject.label, unit: rule.unit };
  if (subject.auraId !== undefined) {
    row.auraId = subject.auraId;
  }
  for (const key of ['kind', 'mine', 'harmful']) {
    if (rule[key] !== undefined) {
      row[key] = rule[key];
    }
  }
  row.on = rule.on;
  // The derived one wins, so a rule carrying a `thresholdConst` cannot also pin a number.
  const threshold = subject.threshold ?? rule.threshold;
  if (threshold !== undefined) {
    row.threshold = threshold;
  }
  for (const key of ['cue', 'banner', 'bout', 'counts']) {
    if (rule[key] !== undefined) {
      row[key] = rule[key];
    }
  }
  return row;
}

function rankOf(cls, order) {
  if (cls === ANY) {
    return ANY_RANK;
  }
  const at = order.indexOf(cls);
  if (at === -1) {
    throw new Error(`rules are filed under "${cls}", which the game has no class for`);
  }
  return at;
}

/** The game's own class order first, then rule id. Both are stable across runs. */
function sorted(rows, order) {
  return [...rows].sort((a, b) => {
    const byClass = rankOf(a.class, order) - rankOf(b.class, order);
    if (byClass !== 0) {
      return byClass;
    }
    return a.id.localeCompare(b.id, 'en');
  });
}

function duplicates(rules) {
  const seen = new Set();
  for (const rule of rules) {
    if (seen.has(rule.id)) {
      throw new Error(`two rules share the id "${rule.id}"`);
    }
    seen.add(rule.id);
  }
}

function sourcesIn(checkout) {
  const classesSource = read(`${checkout}/${CLASSES_SOURCE}`);
  const consts = constTable(checkout);
  return {
    table: abilities(classesSource),
    procs: procAuras(checkout),
    kinds: auraKinds(checkout, classesSource),
    consts,
    applied: encounterAuras(checkout, consts),
    classesSource,
  };
}

function build(checkout, version) {
  const sources = sourcesIn(checkout);
  duplicates(RULES);
  const rows = RULES.map((rule) => rowFor(rule, subjectOf(rule, sources)));
  return {
    format: FORMAT,
    version: FILE_VERSION,
    game: version,
    note: NOTE,
    rules: sorted(rows, classOrder(sources.classesSource)),
  };
}

function main() {
  const checkout = gameArg();
  const version = gameVersion(checkout);
  const file = build(checkout, version);
  writeFileSync(OUTPUT, `${JSON.stringify(file, null, INDENT)}\n`);
  console.log(
    `emberwatch: wrote ${String(file.rules.length)} starter rules from game ${version} to ` +
      'addons/emberwatch/rules.json',
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(`emberwatch: ${reason(err)}`);
    process.exit(1);
  }
}
