/// <reference types="@woc-addons/types" />

// Emberwatch: say which effect on which unit is worth knowing about, and get a tile, a
// cue and a banner when it happens.
//
// The model is the aura LIST, never the aura event. An event carries an id, a source and a
// stack count only on the application path, so a fade usually says nothing where its gain
// said plenty; `world.aurasOn` and `world.partyAuras` carry all four on every row. Nothing
// here subscribes to an aura event. The one thing only an event carries is `refresh`, so a
// tracker counting gains against fades cannot be built on a list; this one reads the
// remaining instead, where a re-application shows as a figure that went back up.
//
// The clock is `woc.onFrame` and the two aura watch keys are deliberately not subscribed:
// `world.on('auras')` signs by id and caster rather than stack count, neither key fires as
// a remaining ticks down, and a party row has no watch key at all. `characterKey` IS
// subscribed, since the rule set and the stored rows belong to one character and the game
// swaps characters inside one page load.
//
// A party row carries an id, a kind and a whole-second remaining, and nothing else: no
// source, so a rule's `mine` clause is DROPPED rather than ignored; no duration, so no
// sweep; no stacks; no school, so `world.dispellable` refuses it. Rows are read anyway,
// because one exists for a member on the far side of the map where an entity does not.
//
// Polarity goes through `world.harmful` rather than arithmetic here: a party row's `neg`
// flag is a sign test on magnitude alone, so a dot, a root, a stun and a silence all
// arrive without it.
//
// What cannot be built, and the pane says so in words: how much damage a control will take
// before it breaks. The soak and the per-hit chance never leave the server, and the wire
// carries a bare presence marker in a field the published `Aura` does not declare.
//
// An effect has its OWN painting where the game ships one, which it did not before game
// 0.39.0: that release added an aura art manifest covering the effects no ability names, the
// mob families among them, and `woc.ui.icon.aura` reads it. What is still true is that the
// family is closed and small, so most of what lands on a unit resolves through nothing: the
// game composites the rest at run time, and the only ability file to point at is filed per
// player class. What a mob does have is a PORTRAIT, so a square with no painting of its own
// carries the face of whatever applied the effect, said out loud in the tooltip and in the
// accessible name rather than left to be read off the picture.
//
// `world.abilities` is deliberately not consulted for a name. An entity's aura carries one
// on the wire; a party row carries none, and a spellbook would answer for your own kit and
// guess the rest, which is a label authoritative on one row and a guess on the next.
//
// The starter table is game content in `rules.json`, generated by `generate.mjs` beside
// this file. `woc.data` hands back `unknown`, so every row goes through `readRule` before
// it can fire anything.

const RULES_FILE = 'rules.json';
const STORE_ROWS = 'rows';
const STORE_OFF = 'disabled';

const DECIMALS = 1;
/** A faded alert has no aura left to count down, so it comes down on a clock. */
const FADED_LINGER_MS = 4000;
/** Starting square and floor. Larger than the kit's 40: this is read at a glance mid-fight. */
const TILE_FLOOR = 48;
/** Stated so a drag can solve back for the square. */
const CAPTION_HEIGHT = 15;
const CAPTION_FONT = 11;
const STRIP_WIDTH = 420;
const DEFAULT_STACK_THRESHOLD = 2;
const SINGLE_STACK = 1;
const PANE_WIDTH = 460;
const PANE_HEIGHT = 380;
const PANE_MIN_WIDTH = 280;
const PANE_MIN_HEIGHT = 190;

/** Drawn in the pane: an engine that alerts on control and stays quiet about this reads as denying it. */
const PANE_NOTES = [
  'A party row carries an id, a kind and whole seconds. No source, so "only mine" is dropped; no duration, so there is no sweep; no stacks; and removability cannot be answered at all.',
  'Nothing here can tell you how much damage a control will take before it breaks. The soak and the per-hit chance stay on the server, and the wire carries only a marker that a soak exists rather than what it is.',
];

const CONDITIONS = ['gained', 'faded', 'stacks', 'expiring'];
/** `party` is the group's rows, which reach across the map. */
const UNITS = ['player', 'target', 'party'];

let starter = [];
/** Whether the table arrived at all, which an empty one is not evidence of. */
let tableRead = false;
let mine = [];
let disabled = new Set();
/** The class the active set was assembled for, so a switch rebuilds it. */
let assembledFor = null;
let active = [];

/** The previous evaluation, which is the only way a fade is visible. */
let previous = new Map();
const alerts = new Map();

/** The first reading is everything already up, which would otherwise arrive as a cue per effect. */
let primed = false;

/**
 * One rule, or null. The loader only checks that `woc.data` parses, so the shape is a claim
 * checked here, and a stored row the player captured is the same kind of claim. A row naming
 * neither an aura id nor a kind nor a polarity is refused: it would fire on everything.
 */
function readRule(value) {
  if (typeof value !== 'object' || value === null) {
    return null;
  }
  const { id, label, unit, on } = value;
  const identified = typeof id === 'string' && id.length > 0 && typeof label === 'string';
  const described = identified && label.length > 0;
  if (!(described && UNITS.includes(unit) && CONDITIONS.includes(on))) {
    return null;
  }
  const rule = { id, label, unit, on, ...optionalOf(value) };
  if (rule.auraId === null && rule.kind === null && rule.harmful === null) {
    return null;
  }
  return rule;
}

function optionalOf(value) {
  return {
    forClass: stringOr(value.class, 'any'),
    auraId: stringOr(value.auraId, null),
    kind: stringOr(value.kind, null),
    mine: flagOr(value.mine),
    harmful: flagOr(value.harmful),
    removable: flagOr(value.removable) === true,
    bout: flagOr(value.bout) === true,
    banner: flagOr(value.banner) === true,
    cue: stringOr(value.cue, null),
    threshold: numberOr(value.threshold),
  };
}

function stringOr(value, fallback) {
  if (typeof value === 'string' && value.length > 0) {
    return value;
  }
  return fallback;
}

function flagOr(value) {
  if (typeof value === 'boolean') {
    return value;
  }
  return null;
}

function numberOr(value) {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value;
  }
  return null;
}

/** A bad row is skipped with a warning rather than the whole list being thrown away. */
function adopt(listed, source) {
  const kept = [];
  for (const [at, row] of listed.entries()) {
    const rule = readRule(row);
    if (rule === null) {
      woc.warn(`${source}: entry ${String(at)} is not a rule, leaving it out`, row);
    } else {
      kept.push(rule);
    }
  }
  return kept;
}

function readFile(file) {
  if (typeof file !== 'object' || file === null || file.format !== 'emberwatch-rules') {
    return null;
  }
  if (!Array.isArray(file.rules)) {
    return null;
  }
  return file.rules;
}

function playerClass() {
  const { player } = woc.world;
  if (player === null || player.kind !== 'player') {
    return null;
  }
  return player.templateId;
}

/** Rebuilt on a class change, never per frame. With no class only the any-class rows are in force. */
function assemble() {
  const cls = playerClass();
  if (cls === assembledFor) {
    return;
  }
  assembledFor = cls;
  active = [...starter, ...mine].filter((rule) => appliesTo(rule, cls));
}

function appliesTo(rule, cls) {
  if (disabled.has(rule.id)) {
    return false;
  }
  return rule.forClass === 'any' || rule.forClass === cls;
}

function reassemble() {
  assembledFor = false;
  assemble();
}

/**
 * The picture for an alert, and whose face it is when it is not the effect's own.
 *
 * Three routes, tried in the order the game's own resolver uses them. The effect's OWN painting
 * comes first, from the aura art manifest game 0.39.0 added: that family is exactly the effects no
 * ability id names, so a mob's aura, an encounter mechanic and a battleground rune are in it, and
 * a square filled from it needs no disclosure because it IS the effect's icon.
 *
 * The family is closed and covers a fraction of what a fight applies, so the two older routes
 * still carry most rows. Ability art is filed per player class, so an effect a mob applied
 * resolves through nothing there: the game composites those icons on a canvas from a module no
 * addon can reach, and a lockout id 404s. A mob's PORTRAIT is a file, and every catalogued
 * template ships one, so the square is filled by the thing that applied the effect rather than
 * left blank. `castBy` is what makes that honest: the tooltip and the accessible name both say
 * whose face it is, because a portrait answers a different question from an ability icon and a
 * square that does not say which is a guess.
 *
 * An npc is deliberately not portrayed. The game draws a crest for one rather than a portrait, so
 * `/ui/mobs/` would 404 and the slot would go back to being empty by a longer route.
 */
function artOf(auraId, sourceId) {
  // The effect's own painting answers for whoever applied it, so this is asked before the
  // caster is even looked up: an aura in that family is the same picture on a mob, on a
  // stranger and on you.
  const own = woc.ui.icon.aura(auraId);
  if (own !== null) {
    return { art: own, castBy: null };
  }
  const caster = woc.world.entities.get(sourceId);
  if (caster === undefined) {
    return { art: null, castBy: null };
  }
  if (caster.kind === 'player') {
    return { art: woc.ui.icon.ability(auraId, caster.templateId), castBy: null };
  }
  if (caster.kind !== 'mob') {
    return { art: null, castBy: null };
  }
  return { art: woc.ui.icon.mob(caster.templateId), castBy: caster.name };
}

/** `mine` is the clause a dot tracker cannot skip. */
function queryFor(rule) {
  const query = rowQueryFor(rule);
  if (rule.mine !== null) {
    query.mine = rule.mine;
  }
  return query;
}

/**
 * A clause the rule does not carry is LEFT OUT rather than passed as null: the query filters
 * test against `undefined`, so a null reads as "match auras whose kind is null", which is none.
 */
function rowQueryFor(rule) {
  const query = {};
  if (rule.auraId !== null) {
    query.id = rule.auraId;
  }
  if (rule.kind !== null) {
    query.kind = rule.kind;
  }
  return query;
}

function keepsAura(rule, aura, hostile) {
  if (rule.harmful !== null && rule.harmful !== woc.world.harmful(aura)) {
    return false;
  }
  return !rule.removable || woc.world.dispellable(aura, hostile);
}

function keepsRow(rule, row) {
  if (rule.removable) {
    return false;
  }
  return rule.harmful === null || rule.harmful === woc.world.harmful(row);
}

function candidateKey(rule, unitKey, auraId, sourceId) {
  return `${rule.id}|${unitKey}|${auraId}|${String(sourceId)}`;
}

function fromAura(rule, unit, unitKey, aura) {
  return {
    key: candidateKey(rule, unitKey, aura.id, aura.sourceId),
    rule,
    unitKey,
    who: unit.name,
    entityId: unit.id,
    row: false,
    auraId: aura.id,
    name: aura.name,
    derivedName: false,
    kind: aura.kind,
    school: aura.school,
    stacks: aura.stacks ?? SINGLE_STACK,
    remaining: aura.remaining,
    duration: aura.duration,
    encounterOwned: aura.unbreakableControl === true,
    ...artOf(aura.id, aura.sourceId),
  };
}

/** Null rather than a default: the display has to tell "none on this effect" from "a row cannot say". */
function fromRow(rule, member, row) {
  const unitKey = `party:${String(member.pid)}`;
  return {
    key: candidateKey(rule, unitKey, row.id, 0),
    rule,
    unitKey,
    who: member.name,
    entityId: null,
    row: true,
    auraId: row.id,
    // `shadow_word_pain` to "Shadow Word Pain", which is a GUESS and is labelled as one.
    name: woc.fmt.titleCase(row.id),
    derivedName: true,
    kind: row.kind,
    school: null,
    stacks: null,
    remaining: row.remaining ?? null,
    duration: null,
    encounterOwned: false,
    art: null,
    castBy: null,
  };
}

/** Which way removability points: a benefit comes off a hostile, a harm off a friendly. */
function hostility(unit) {
  return unit.hostile === true;
}

function entityMatches(rule, token) {
  const unit = woc.world.unit(token);
  if (unit === null) {
    return [];
  }
  const found = [];
  for (const aura of woc.world.aurasOn(token, queryFor(rule))) {
    if (keepsAura(rule, aura, hostility(unit))) {
      found.push(fromAura(rule, unit, token, aura));
    }
  }
  return found;
}

function partyMatches(rule) {
  const found = [];
  for (const member of woc.world.party?.members ?? []) {
    for (const row of woc.world.partyAuras(member.pid, rowQueryFor(rule))) {
      if (keepsRow(rule, row)) {
        found.push(fromRow(rule, member, row));
      }
    }
  }
  return found;
}

function ruleRuns(rule) {
  if (rule.on === 'expiring' && !woc.settings.expiring) {
    return false;
  }
  return !rule.bout || woc.world.match !== null;
}

function candidatesFor(rule) {
  if (!ruleRuns(rule)) {
    return [];
  }
  if (rule.unit === 'party') {
    return partyMatches(rule);
  }
  return entityMatches(rule, rule.unit);
}

function expiryThreshold(rule) {
  return rule.threshold ?? woc.settings['expiring-seconds'];
}

function stackThreshold(rule) {
  return rule.threshold ?? DEFAULT_STACK_THRESHOLD;
}

/** `gained` holds while the effect is there, so the tile is a readout rather than a flash. */
function holds(found) {
  const { rule } = found;
  if (rule.on === 'gained') {
    return true;
  }
  if (rule.on === 'stacks') {
    return found.stacks !== null && found.stacks >= stackThreshold(rule);
  }
  if (rule.on === 'expiring') {
    return found.remaining !== null && found.remaining <= expiryThreshold(rule);
  }
  return false;
}

function fractionOf(found) {
  if (found.duration === null || found.duration <= 0 || found.remaining === null) {
    return null;
  }
  return Math.min(found.remaining / found.duration, 1);
}

function stackCount(found) {
  if (found.stacks === null || found.stacks <= SINGLE_STACK) {
    return null;
  }
  return found.stacks;
}

function toneOf(found) {
  if (found.rule.banner) {
    return 'danger';
  }
  if (found.rule.on === 'expiring') {
    return 'warn';
  }
  return 'default';
}

/** A plain emit: nothing follows this topic, so there is no ask to answer. */
function announce(found, state) {
  woc.bus.emit('alert', {
    ruleId: found.rule.id,
    unit: found.unitKey,
    auraId: found.auraId,
    state,
  });
}

function bannerFor(found) {
  woc.ui.banner(found.rule.label, {
    kind: 'danger',
    size: woc.settings['banner-size'],
    detail: `on ${found.who}`,
  });
}

/** Silent while priming, or everything already up would arrive at once as news. */
function sound(found) {
  if (!primed) {
    return;
  }
  if (found.rule.cue !== null) {
    woc.sound.play(found.rule.cue, { volume: woc.settings.volume });
  }
  if (found.rule.banner) {
    bannerFor(found);
  }
}

function lingerUntil(now, momentary) {
  if (momentary) {
    return now + FADED_LINGER_MS;
  }
  return null;
}

function raise(found, now, momentary) {
  const existing = alerts.get(found.key);
  if (existing === undefined) {
    alerts.set(found.key, { found, at: now, until: lingerUntil(now, momentary) });
    sound(found);
    announce(found, 'active');
    return;
  }
  existing.found = found;
}

function clear(key) {
  const record = alerts.get(key);
  if (record === undefined) {
    return;
  }
  alerts.delete(key);
  announce(record.found, 'cleared');
}

function collect() {
  const current = new Map();
  for (const rule of active) {
    for (const found of candidatesFor(rule)) {
      current.set(found.key, found);
    }
  }
  return current;
}

/** A fade is the previous reading minus this one: the effect is not in the reading that follows. */
function fades(current, now) {
  for (const [key, found] of previous) {
    if (found.rule.on === 'faded' && !current.has(key)) {
      raise(found, now, true);
    }
  }
}

function states(current, now) {
  for (const [key, found] of current) {
    if (found.rule.on !== 'faded' && holds(found)) {
      raise(found, now, false);
    } else {
      clear(key);
    }
  }
}

/** An effect gone between two readings is in neither loop above, and would sit there for the session. */
function orphans(current) {
  for (const [key, record] of alerts) {
    if (record.until === null && !current.has(key)) {
      clear(key);
    }
  }
}

function retire(now) {
  for (const [key, record] of alerts) {
    if (record.until !== null && now >= record.until) {
      clear(key);
    }
  }
}

function evaluate(now) {
  assemble();
  const current = collect();
  states(current, now);
  orphans(current);
  fades(current, now);
  retire(now);
  previous = current;
  primed = woc.world.player !== null;
}

const list = document.createElement('div');
list.className = 'woc-ew-list';
list.style.display = 'flex';
list.style.alignItems = 'flex-start';
list.style.gap = '6px';

/** A budget nobody can see is a budget that lies. */
const overflow = document.createElement('span');
overflow.className = 'woc-ew-overflow';
overflow.style.fontSize = `${String(CAPTION_FONT)}px`;
overflow.style.alignSelf = 'center';
overflow.style.whiteSpace = 'nowrap';

function stripHeight(size) {
  return size + CAPTION_HEIGHT;
}

let tileSize = TILE_FLOOR;

/** Bare, since the tiles are the display. The title survives as the label unlock mode shows. */
const frame = woc.ui.frame({
  id: 'alerts',
  title: 'Emberwatch',
  width: STRIP_WIDTH,
  // Stated because a content-sized frame is never given a box, so there would be nothing to drag.
  height: stripHeight(TILE_FLOOR),
  density: 'bare',
  save: true,
  resizable: true,
  toggleKey: 'toggle',
  // Constants, never the current alert count: that would trap a player who sized it during a pull.
  minWidth: TILE_FLOOR,
  minHeight: stripHeight(TILE_FLOOR),
  onMove: (box) => {
    resize(box.h);
  },
});
frame.body.appendChild(list);
list.appendChild(overflow);

/** The floor is applied here as well as declared, since a box also arrives from a restore or a clamp. */
function resize(height) {
  // One unit under a fixed band, which is what `extra` is for: the caption is space the
  // square never gets, and the floor holds for a box from anywhere.
  tileSize = woc.ui.units(height, { extra: CAPTION_HEIGHT, min: TILE_FLOOR });
}

/** Read back off the element rather than held beside it: a pin and its cell share the one element. */
function sizeCell(cell) {
  const width = `${String(tileSize)}px`;
  if (cell.el.style.width === width) {
    return;
  }
  cell.el.style.width = width;
  cell.ui.update({ size: tileSize });
}

/** Which reading this came off, which is what a player checks a gap against. */
function sourceLine(found) {
  if (found.row) {
    return {
      text: 'Read off a party row: whole seconds, no stacks, no source, and at most eight effects.',
      tone: 'warn',
    };
  }
  return { text: 'Read off the unit itself.', tone: 'muted' };
}

function conditionLine(found) {
  const { rule } = found;
  if (rule.on === 'stacks') {
    return `Fires at ${String(stackThreshold(rule))} applications or more.`;
  }
  if (rule.on === 'expiring') {
    return `Fires with ${String(expiryThreshold(rule))}s or less left.`;
  }
  if (rule.on === 'faded') {
    return 'Fires when the effect goes.';
  }
  return 'Fires while the effect is there.';
}

function remainingLine(found) {
  if (found.remaining === null) {
    return { text: 'No remaining time on this reading.', tone: 'warn' };
  }
  return `${found.remaining.toFixed(DECIMALS)}s left.`;
}

function extraLines(found) {
  const lines = [];
  if (found.castBy !== null) {
    lines.push({
      text: `Pictured: ${found.castBy}, which applied it. A mob's effect has no icon of its own.`,
      tone: 'muted',
    });
  }
  if (found.encounterOwned) {
    lines.push({ text: 'The encounter owns this one: nothing you do breaks it.', tone: 'danger' });
  }
  if (found.derivedName) {
    lines.push({
      text: `Name derived from "${found.auraId}", not read from the wire.`,
      tone: 'muted',
    });
  }
  if (found.rule.unit === 'party' && found.rule.mine !== null) {
    lines.push({ text: '"Only mine" was dropped: a party row carries no source.', tone: 'warn' });
  }
  return lines;
}

/** A function, so it answers with what is left NOW rather than at the moment the tile was built. */
function tooltipFor(key) {
  const record = alerts.get(key);
  if (record === undefined) {
    return 'This alert has gone.';
  }
  const { found } = record;
  return {
    title: found.name,
    icon: found.art,
    lines: [
      `${found.rule.label}, on ${found.who}`,
      conditionLine(found),
      remainingLine(found),
      ...extraLines(found),
      sourceLine(found),
    ],
  };
}

function createCell(found) {
  const tile = woc.ui.tile({ label: labelFor(found), className: 'woc-ew-tile' });
  const el = document.createElement('div');
  el.className = 'woc-ew-cell';
  el.dataset.alert = found.key;
  el.style.display = 'flex';
  el.style.flexDirection = 'column';
  el.style.alignItems = 'center';
  // A flex item shrinks by default, so a narrowed strip would squash the squares out of true.
  el.style.flexShrink = '0';
  const caption = document.createElement('span');
  caption.className = 'woc-ew-caption';
  caption.style.overflow = 'hidden';
  caption.style.textOverflow = 'ellipsis';
  caption.style.whiteSpace = 'nowrap';
  caption.style.maxWidth = '100%';
  caption.style.fontSize = `${String(CAPTION_FONT)}px`;
  // Both directions, because the drag solves the strip's height back for the square.
  caption.style.height = `${String(CAPTION_HEIGHT)}px`;
  caption.style.lineHeight = `${String(CAPTION_HEIGHT)}px`;
  el.append(tile.el, caption);
  const cell = {
    ui: tile,
    el,
    caption,
    destroy: () => {
      tile.destroy();
      el.remove();
    },
  };
  sizeCell(cell);
  woc.ui.tooltip(el, () => tooltipFor(found.key));
  return cell;
}

/** The anchor is the cell's own, so a pin is one thing to its list and goes down in one piece. */
function createPin(entry) {
  const cell = createCell(entry.found);
  const anchor = woc.ui.anchor3d(
    { unit: entry.found.entityId, over: 'head' },
    { className: 'woc-ew-pin' },
  );
  anchor.el.appendChild(cell.el);
  return {
    ...cell,
    destroy: () => {
      cell.destroy();
      anchor.destroy();
    },
  };
}

/** A tile is all art, so everything it says has to be in its accessible name too, the face included. */
function labelFor(found) {
  const said = `${found.rule.label}: ${found.name} on ${found.who}`;
  if (found.castBy === null) {
    return said;
  }
  return `${said}, from ${found.castBy}`;
}

/** Full rather than empty with no denominator: an empty square reads as an effect already gone. */
function sweepOf(found) {
  return fractionOf(found) ?? 1;
}

function paint(cell, entry) {
  const { found } = entry;
  sizeCell(cell);
  cell.caption.textContent = found.who;
  cell.ui.update({
    label: labelFor(found),
    icon: found.art,
    fraction: sweepOf(found),
    // `8`, or `2m` where a square has no room to spell it out, and empty for a party row,
    // whose remaining is null until the member is close enough to have one.
    value: woc.fmt.duration(found.remaining),
    count: stackCount(found),
    school: found.school,
    tone: toneOf(found),
  });
}

/** By arrival, never by remaining: sorting on remaining reorders the strip while it is being read. */
function newestFirst(a, b) {
  return b.at - a.at;
}

function ordered() {
  const rows = [...alerts.entries()].sort(([, a], [, b]) => newestFirst(a, b));
  const budget = Math.max(Math.round(woc.settings['max-tiles']), 1);
  return {
    shown: rows.slice(0, budget).map(([key, record]) => ({ key, found: record.found })),
    hidden: Math.max(rows.length - budget, 0),
  };
}

/** A party row has no entity to sit over, so it stays on the strip whatever the setting says. */
function onStrip(entry) {
  return woc.settings.placement !== 'unit' || entry.found.entityId === null;
}

/**
 * Two lists, because with a `parent` an unshown row's element is removed from the document:
 * a row that anchors itself needs a list with no parent.
 */
const strip = woc.ui.list({
  parent: list,
  key: (entry) => entry.key,
  create: (entry) => createCell(entry.found),
  update: paint,
});

const pinned = woc.ui.list({
  key: (entry) => entry.key,
  create: createPin,
  update: paint,
});

function drawOverflow(hidden) {
  if (hidden === 0) {
    overflow.textContent = '';
    return;
  }
  overflow.textContent = `+${String(hidden)} more`;
}

/** Never placed: the list inserts each square before the child at that index, so it stays last. */
function draw() {
  const { shown, hidden } = ordered();
  strip.sync(shown.filter(onStrip));
  pinned.sync(shown.filter((entry) => !onStrip(entry)));
  drawOverflow(hidden);
}

/** The pins come down too: they are outside the frame, so a hidden strip would leave them drawn. */
function blank() {
  if (strip.size === 0 && pinned.size === 0 && overflow.textContent === '') {
    return;
  }
  strip.clear();
  pinned.clear();
  overflow.textContent = '';
}

/** Both bounds are stated so the floor is one row, not however many rules were in force at first open. */
const paneBody = document.createElement('div');
paneBody.className = 'woc-ew-rules';
paneBody.style.display = 'flex';
paneBody.style.flexDirection = 'column';
paneBody.style.gap = '6px';

const pane = woc.ui.frame({
  id: 'rules',
  title: 'Emberwatch rules',
  width: PANE_WIDTH,
  height: PANE_HEIGHT,
  minWidth: PANE_MIN_WIDTH,
  minHeight: PANE_MIN_HEIGHT,
  resizable: true,
  closable: true,
  save: true,
  visible: false,
});
pane.body.appendChild(paneBody);

const paneRows = [];

function note(text) {
  const el = document.createElement('div');
  el.className = 'woc-ew-note';
  el.style.fontSize = `${String(CAPTION_FONT)}px`;
  el.style.opacity = '0.7';
  el.textContent = text;
  return el;
}

function subjectOf(rule) {
  if (rule.auraId !== null) {
    return rule.auraId;
  }
  if (rule.kind !== null) {
    return rule.kind;
  }
  if (rule.harmful === true) {
    return 'any harmful effect';
  }
  return 'any beneficial effect';
}

function describe(rule) {
  const parts = [`${rule.unit}: ${subjectOf(rule)}`, rule.on];
  if (rule.mine === true && rule.unit !== 'party') {
    parts.push('mine only');
  }
  if (rule.bout) {
    parts.push('in a bout only');
  }
  return parts.join(', ');
}

function removeRow(rule) {
  mine = mine.filter((row) => row.id !== rule.id);
  persist(STORE_ROWS, mine);
  reassemble();
  fillPane();
}

/** Only for a row the player captured. */
function removeButton(rule) {
  const button = document.createElement('button');
  button.type = 'button';
  button.className = 'woc-btn';
  button.textContent = 'Remove';
  button.addEventListener('click', () => {
    removeRow(rule);
  });
  return button;
}

function setEnabled(rule, on) {
  if (on) {
    disabled.delete(rule.id);
  } else {
    disabled.add(rule.id);
  }
  persist(STORE_OFF, [...disabled]);
  reassemble();
}

function paneRow(rule, own) {
  const el = document.createElement('div');
  el.className = 'woc-ew-rule';
  el.dataset.rule = rule.id;
  el.style.display = 'flex';
  el.style.alignItems = 'center';
  el.style.justifyContent = 'space-between';
  el.style.gap = '8px';
  const field = woc.ui.field.checkbox({
    label: rule.label,
    value: !disabled.has(rule.id),
    onChange: (on) => {
      setEnabled(rule, on);
    },
  });
  el.append(field.el, note(describe(rule)));
  if (own) {
    el.appendChild(removeButton(rule));
  }
  paneRows.push({ el, field });
  return el;
}

/** Includes rules another class owns, since a switched-off row still has to be findable. */
function paneRules() {
  const cls = playerClass();
  return [...starter, ...mine].filter((rule) => rule.forClass === 'any' || rule.forClass === cls);
}

/**
 * An empty list is three different facts: no table yet, no class yet, or nothing shipped for
 * this class. `tableRead` separates the first from the third, which otherwise look alike.
 */
function emptyReason() {
  if (!tableRead) {
    return 'The starter rules have not been read yet.';
  }
  if (playerClass() === null) {
    return 'No class yet: the starter set is picked once you are in the world.';
  }
  return 'No rules for this character yet. Capture one off your target to add the first.';
}

function fillPane() {
  for (const row of paneRows.splice(0)) {
    row.field.destroy();
    row.el.remove();
  }
  paneBody.replaceChildren();
  const rules = paneRules();
  const ownIds = new Set(mine.map((rule) => rule.id));
  if (rules.length === 0) {
    paneBody.appendChild(note(emptyReason()));
  }
  for (const rule of rules) {
    paneBody.appendChild(paneRow(rule, ownIds.has(rule.id)));
  }
  for (const line of PANE_NOTES) {
    paneBody.appendChild(note(line));
  }
}

/** Harmful first, then yours, then longest: a dot you are keeping up is what a rule is usually for. */
function priority(aura, playerId) {
  const harm = woc.world.harmful(aura);
  const ours = aura.sourceId === playerId;
  return [harm, ours, aura.remaining];
}

function betterAura(a, b, playerId) {
  const left = priority(a, playerId);
  const right = priority(b, playerId);
  for (const [at, value] of left.entries()) {
    if (value !== right[at]) {
      return value > right[at];
    }
  }
  return false;
}

function bestOnTarget() {
  const playerId = woc.world.player?.id ?? null;
  let best = null;
  for (const aura of woc.world.aurasOn('target')) {
    if (best === null || betterAura(aura, best, playerId)) {
      best = aura;
    }
  }
  return best;
}

/** `mine` is stamped from who applied it: "watch my dot" and "watch this debuff" are different rules. */
function ruleFromAura(aura, playerId) {
  return {
    id: `own-${aura.id}-${String(woc.wallClock())}`,
    label: aura.name,
    class: playerClass() ?? 'any',
    unit: 'target',
    auraId: aura.id,
    mine: aura.sourceId === playerId && playerId !== null,
    on: 'expiring',
    cue: 'buff_apply',
  };
}

function capture() {
  const aura = bestOnTarget();
  if (aura === null) {
    woc.ui.toast('Nothing on your target to watch.', { kind: 'warn' });
    return;
  }
  const rule = readRule(ruleFromAura(aura, woc.world.player?.id ?? null));
  if (rule === null) {
    woc.warn('could not turn that effect into a rule', aura);
    return;
  }
  mine = [...mine, rule];
  persist(STORE_ROWS, mine);
  reassemble();
  fillPane();
  woc.ui.toast(`Watching ${aura.name} on your target.`);
}

/** A per-character write rejects before world entry. Both callers are gestures, so this is a guard. */
async function write(key, value) {
  await woc.world.ready;
  await woc.storage.character.set(key, value);
}

/** For callers that cannot await. */
function persist(key, value) {
  write(key, value).catch((err) => {
    woc.warn(`could not save "${key}"`, err);
  });
}

/** Checked exactly as the shipped file is. */
function readStoredRules(stored) {
  if (!Array.isArray(stored)) {
    return [];
  }
  return adopt(stored, STORE_ROWS);
}

function readStoredOff(stored) {
  if (!Array.isArray(stored)) {
    return new Set();
  }
  return new Set(stored.filter((id) => typeof id === 'string'));
}

/** A per-character read waits for the character, so this settles with the rows of whoever logged in. */
async function restore() {
  const [rows, off] = await Promise.all([
    woc.storage.character.get(STORE_ROWS, null),
    woc.storage.character.get(STORE_OFF, null),
  ]);
  mine = readStoredRules(rows);
  disabled = readStoredOff(off);
  reassemble();
  fillPane();
}

function load() {
  restore().catch((err) => {
    woc.warn("could not read this character's own rules back", err);
  });
}

async function boot() {
  const rules = readFile(await woc.data(RULES_FILE));
  if (rules === null) {
    throw new Error(`${RULES_FILE} carries no "rules" array`);
  }
  starter = adopt(rules, RULES_FILE);
  tableRead = true;
  reassemble();
  fillPane();
}

// The engine runs while the strip is hidden: the cue and the banner are the half that works
// when nobody is looking at the overlay. Only the drawing is skipped.
woc.onFrame(() => {
  evaluate(woc.now());
  if (frame.visible) {
    draw();
  } else {
    blank();
  }
});

// A character switch changes both halves: the class the starter rows are picked by, and the rows.
woc.world.on('characterKey', load);

woc.keys.bind('capture', capture);

// The keybinds are spent on the two things done mid-fight, so the pane opens from the menu.
woc.ui.menuEntry({
  id: 'rules',
  label: 'Emberwatch rules',
  onClick: () => {
    pane.show();
  },
});

// Settings are read while the next frame is built, so a change lands with nothing torn down. The
// pane is the exception: its rows come from the rule set rather than from a setting.
fillPane();

boot().catch((err) => {
  woc.error('could not read the starter rules, so only your own rows will fire', err);
});

// `icon.aura` answers null until the manifest lands, unlike the ability and item builders, so
// this is read at start rather than on the first row. An alert is drawn at the moment the
// effect appears, so a row that raced the read would keep the caster's face for as long as it
// was up; starting the read here is what keeps that to the first moments of a session.
woc.ui.icon.preloadAuras().catch(() => {
  // Documented never to reject. Caught anyway, because a broken promise here would be an
  // unhandled rejection in the page the game is running in.
});

load();
