// Reading the game's own SFX runtime pack.
//
// The game publishes /audio/sfx/runtime-pack.json, which is what its audio
// engine loads, so taking cue names from it means the loader's list cannot drift
// from what is actually deployed. It also carries the two things a directory
// listing could not: the per-clip gain the game normalized each sound to, and
// the hashed URL that makes the browser cache correct across a game update.
//
// A cue is NOT a file. The pack collapses a numbered family into one cue with
// several variants, so 432 files are 220 cues: `combat_block` has three, and
// playing it picks one the way the game does. Anything that counted files would
// offer addon authors 212 cue names that do not exist.
//
// Hand-validated rather than parsed with zod, which is host-only and must never
// reach this bundle.

import { diagError } from '../../shared/diag.ts';

/** The `format` field the game stamps, and the one schema version understood. */
const FORMAT = 'woc-sfx-runtime-pack';
const SCHEMA_VERSION = 1;

const PACK_URL = '/audio/sfx/runtime-pack.json';

const DEFAULT_GAIN = 1;
const DEFAULT_RATE = 1;

interface SoundClip {
  /** At least one. Playing the cue picks one of them. */
  variants: readonly string[];
  /** The loudness normalization the game applies to this clip. */
  gain: number;
  playbackRate: number;
}

type SoundPack = ReadonlyMap<string, SoundClip>;

type PackResult = { ok: true; pack: SoundPack } | { ok: false; reason: string };

function asRecord(value: unknown): Record<string, unknown> | null {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    return null;
  }
  return value as Record<string, unknown>;
}

/**
 * One field off a parsed record, and the only place this file indexes a key.
 *
 * The key arrives as a value rather than in the brackets: dot access on an index
 * signature is a type error under `noPropertyAccessFromIndexSignature`, and a
 * string literal in the brackets is what `useLiteralKeys` refuses.
 */
function field(record: Record<string, unknown> | null, key: string): unknown {
  if (record === null) {
    return;
  }
  return record[key];
}

/** A positive finite number, or the fallback. Zero gain would be a silent cue. */
function positiveNumber(value: unknown, fallback: number): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) {
    return fallback;
  }
  return value;
}

function readVariants(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  const urls: string[] = [];
  for (const entry of value) {
    const url = field(asRecord(entry), 'url');
    if (typeof url === 'string' && url.length > 0) {
      urls.push(url);
    }
  }
  return urls;
}

/**
 * Turn one `clips` entry into a clip, or null if it has no playable variant.
 *
 * A malformed entry is dropped rather than failing the pack. The pack is
 * regenerated by the game's build on every release, so the realistic failure is
 * one new row the loader does not understand, and losing one cue is a better
 * outcome than losing all 220.
 */
function readClip(value: unknown): SoundClip | null {
  const clip = asRecord(value);
  if (clip === null) {
    return null;
  }
  const variants = readVariants(field(clip, 'variants'));
  if (variants.length === 0) {
    return null;
  }
  return {
    variants,
    gain: positiveNumber(field(clip, 'gain'), DEFAULT_GAIN),
    playbackRate: positiveNumber(field(clip, 'playbackRate'), DEFAULT_RATE),
  };
}

/**
 * Parse a fetched pack.
 *
 * An unrecognized `format` or `version` is refused rather than read
 * optimistically: the caller then falls back to plain per-cue URLs, which is
 * lossy but correct, where a mis-parse would produce URLs that 404.
 */
function parseSoundPack(input: unknown): PackResult {
  const root = asRecord(input);
  if (root === null) {
    return { ok: false, reason: 'the sound pack is not an object' };
  }
  const format = field(root, 'format');
  if (format !== FORMAT) {
    return { ok: false, reason: `expected format '${FORMAT}', got ${String(format)}` };
  }
  const version = field(root, 'version');
  if (version !== SCHEMA_VERSION) {
    return {
      ok: false,
      reason: `sound pack schema ${String(version)} is newer than this loader understands`,
    };
  }

  const clips = asRecord(field(root, 'clips'));
  if (clips === null) {
    return { ok: false, reason: 'the sound pack has no clips' };
  }

  const pack = new Map<string, SoundClip>();
  for (const [cue, value] of Object.entries(clips)) {
    const clip = readClip(value);
    if (clip !== null) {
      pack.set(cue, clip);
    }
  }
  if (pack.size === 0) {
    return { ok: false, reason: 'the sound pack held no playable clips' };
  }
  return { ok: true, pack };
}

/**
 * The URL for a cue with no pack entry.
 *
 * Degraded and honestly so: it resolves only for a cue whose name is its own
 * file, and a family cue such as `combat_block` has no `combat_block.mp3` to
 * find. It also loses the game's per-clip gain and its cache-busting hash. This
 * is the path taken when the pack cannot be fetched at all.
 */
/**
 * Fetch and parse the game's pack, or an empty one having said why it is empty.
 *
 * Here rather than in the engine because it is the other half of what this module
 * is: the URL and the parser are already here, and the engine's business is
 * playback. Every failure is reported and then swallowed, since the caller carries
 * on with fallback URLs, which is lossy but audible, where rejecting would leave
 * the engine with nothing to do but report the same thing again.
 */
async function fetchSoundPack(fetchJson: (url: string) => Promise<unknown>): Promise<SoundPack> {
  let raw: unknown;
  try {
    raw = await fetchJson(PACK_URL);
  } catch (err) {
    diagError('could not fetch the game sound pack, cue names will be unavailable', err);
    return new Map();
  }
  const result = parseSoundPack(raw);
  if (!result.ok) {
    diagError(`could not read the game sound pack: ${result.reason}`);
    return new Map();
  }
  return result.pack;
}

function fallbackCueUrl(cue: string): string {
  return `/audio/sfx/${cue}.mp3`;
}

export type { PackResult, SoundClip, SoundPack };
export { fallbackCueUrl, fetchSoundPack, PACK_URL, parseSoundPack };
