// Turning the game's harmful-aura kind set into a value module and a union.
//
// The parse and the rendering live here, apart from the file reads, so a Vitest
// suite can drive both without a checkout. `tools/aura-kinds.mjs` is the CLI
// around them, the same split as cues-core.ts and icons-core.ts.
//
// WHY THIS READS A CHECKOUT rather than an endpoint, which is where it departs
// from its two precedents. The classifier is a sim module bundled into the play
// chunk and no object on `__game` exposes it, and nothing aura-shaped is served
// under `/ui/`. So the set exists only in the game's source, and the price of
// that is the one thing an endpoint gives for free: nothing 404s to say the
// checkout is stale. `--game` is therefore required and never defaulted, and the
// game version is written into both headers so a regenerate diff says which
// release the set describes.
//
// TWO OUTPUTS, which is the other departure. `cues` and `icons` generate types
// only, because the runtime re-reads the same manifest over HTTP at run time.
// There is no endpoint here, so the runtime has to carry the VALUE as well.
//
// The parse is over the source TEXT rather than an import of the module. The
// game's imports are extensionless and one of them is a value import, so Node's
// type stripping cannot resolve them without the game's own resolver config. A
// text parse also fails LOUDLY on a refactor, where an import would fail
// obscurely.

import { byCodePoint } from './icons-core.ts';

const GENERATED_VALUES = 'loader/src/shared/aura-kinds.generated.ts';
const GENERATED_TYPES = 'packages/types/aura-kinds.generated.d.ts';

/** Where the rule lives in the game repository. Relative to the checkout root. */
const SOURCE = 'src/sim/aura_classify.ts';

/** The declaration this parse is anchored on. A refactor that moves it throws. */
const DECLARED = 'DEBUFF_AURA_KINDS';
const OPEN = `export const ${DECLARED}: ReadonlySet<AuraKind> = new Set<AuraKind>([`;
const CLOSE = '\n]);';

const NAME_RE = /'([a-z0-9_]+)'/;
const COMMENT = '//';

/** One line of the set body: a quoted name, or nothing when blank or a comment. */
function kindOnLine(line: string): string[] {
  const trimmed = line.trim();
  if (trimmed.length === 0 || trimmed.startsWith(COMMENT)) {
    return [];
  }
  const found = NAME_RE.exec(trimmed);
  if (found?.[1] === undefined) {
    throw new Error(`${SOURCE} has a set entry this parse does not understand: ${trimmed}`);
  }
  return [found[1]];
}

/**
 * Every kind the game classifies as harmful by nature, in source order, deduped.
 *
 * Throws on anything unexpected rather than answering short, for the reason the
 * cue reader does: a set that quietly loses names generates a file that
 * compiles, publishes, and misclassifies effects in every addon that filters on
 * polarity. A line inside the block that carries no quoted name and is neither
 * blank nor a comment is a parse FAILURE rather than something to skip, because
 * that is what a refactor looks like from in here.
 */
function debuffKinds(source: string): string[] {
  const open = source.indexOf(OPEN);
  if (open === -1) {
    throw new Error(`${SOURCE} no longer declares ${DECLARED} the expected way`);
  }
  const body = source.slice(open + OPEN.length);
  const close = body.indexOf(CLOSE);
  if (close === -1) {
    throw new Error(`${SOURCE} has an unterminated ${DECLARED} set`);
  }
  const unique = [...new Set(body.slice(0, close).split('\n').flatMap(kindOnLine))];
  if (unique.length === 0) {
    throw new Error(`${SOURCE} names no harmful aura kinds`);
  }
  return unique;
}

/**
 * What both headers record: which release of the game the set was read out of.
 *
 * The version is the whole staleness story here. A served manifest answers 404
 * when it moves; a checkout answers whatever was last pulled into it, so the
 * only thing a reviewer can check on a regenerate diff is which release this
 * claims to describe.
 */
function readFrom(version: string): string {
  return `${SOURCE} in world-of-claudecraft ${version}`;
}

/** The runtime's copy of the set. Sorted, so a regenerate diff is one line per kind. */
function renderKindValues(kinds: readonly string[], version: string): string {
  const members = [...kinds]
    .sort(byCodePoint)
    .map((kind) => `  '${kind}',`)
    .join('\n');
  return `// Generated by tools/aura-kinds.mjs from ${readFrom(version)}. Do not hand-edit.
//
// Every aura kind the game treats as harmful BY NATURE, whatever its magnitude.
// Regenerate with \`pnpm aura-kinds\` after a game release changes the set.
//
// This is half of the game's rule and not the whole of it. The other half is a
// sign test: a \`buff_*\` kind whose magnitude went negative is a drain and is
// harmful too, which is why a mob sapping attack power does not need its own
// kind. \`world/auras.ts\` is where the two clauses are put back together, and it
// is the only place that should: an addon that reads a set writes its own
// classifier, which is the drift the game's own one-classifier rule exists to
// prevent, one level out.
//
// A kind added by a release this file predates reads as NOT harmful. That is the
// conservative direction and the published contract says so: an effect nobody
// classified is not offered as something to remove.

const DEBUFF_AURA_KINDS: ReadonlySet<string> = new Set([
${members}
]);

export { DEBUFF_AURA_KINDS };
`;
}

/** The same names as a union, for an author writing a comparison against one. */
function renderKindTypes(kinds: readonly string[], version: string): string {
  const union = [...kinds]
    .sort(byCodePoint)
    .map((kind) => `  | '${kind}'`)
    .join('\n');
  return `// Generated by tools/aura-kinds.mjs from ${readFrom(version)}. Do not hand-edit.
//
// Every aura kind the game treats as harmful by nature, which is what
// \`world.harmful\` answers true for without consulting a magnitude. Regenerate
// with \`pnpm aura-kinds\` after a game release changes the set.
//
// Autocomplete only. Ask \`world.harmful(aura)\` rather than testing membership
// yourself: the game's rule has a second clause this union cannot carry, since a
// \`buff_*\` kind with a negative magnitude is a drain and is harmful too.
//
// OPEN, like every generated union here. The set is content, a game release adds
// to it before these types catch up, and a published type must never be able to
// break a working addon.

export type KnownHarmfulAuraKind =
${union};

export type HarmfulAuraKind = KnownHarmfulAuraKind | (string & Record<never, never>);
`;
}

export {
  debuffKinds,
  GENERATED_TYPES,
  GENERATED_VALUES,
  kindOnLine,
  renderKindTypes,
  renderKindValues,
  SOURCE,
};
