// Turning the game's sound pack into a cue-name union authors can autocomplete.
//
// The reading and the rendering live here, apart from the fetch, so a Vitest
// suite can drive both without a network. `tools/cues.mjs` is the CLI around
// them, the same split as manifests.ts and serve-core.ts.
//
// A cue is not a file, and the difference is the whole reason this is generated
// from the pack rather than from a directory listing: the pack collapses a
// numbered family into one cue with several variants, so the deployed files
// outnumber the cues by more than two to one. Anything counting files would
// offer authors a couple of hundred names that do not resolve.

const GENERATED = 'packages/types/cues.generated.d.ts';

/** The pack's own format tag, so a wrong URL fails loudly rather than emptily. */
const FORMAT = 'woc-sfx-runtime-pack';

/** Any total order will do: the sort exists to keep the generated file stable. */
function byCodePoint(a: string, b: string): number {
  if (a === b) {
    return 0;
  }
  if (a < b) {
    return -1;
  }
  return 1;
}

/**
 * Every cue the pack names, sorted and deduplicated.
 *
 * Throws rather than returning an empty list for a payload that is not a pack.
 * An empty union would generate a file that compiles, publishes, and quietly
 * takes autocomplete away from every author.
 */
function cueNames(pack: unknown): string[] {
  if (typeof pack !== 'object' || pack === null) {
    throw new Error('the sound pack is not an object');
  }
  const record = pack as { format?: unknown; clips?: unknown };
  if (record.format !== FORMAT) {
    throw new Error(`expected a ${FORMAT} payload, got format ${String(record.format)}`);
  }
  const { clips } = record;
  if (typeof clips !== 'object' || clips === null) {
    throw new Error('the sound pack has no clips');
  }
  const names = [...new Set(Object.keys(clips))].sort(byCodePoint);
  if (names.length === 0) {
    throw new Error('the sound pack names no cues');
  }
  return names;
}

/** The generated module's text, for a given cue list and where it came from. */
function renderCueTypes(names: readonly string[], source: string): string {
  const union = names.map((name) => `  | '${name}'`).join('\n');
  return `// Generated by tools/cues.mjs from ${source}. Do not hand-edit.
//
// Every sound cue the deployed game ships, which is what \`woc.sound.play\`
// autocompletes. Regenerate with \`pnpm cues\` after a game release adds one.
//
// A cue is not a file: a numbered family such as 'combat_block' is one cue with
// several variants, and playing it picks one the way the game does.

export type KnownCue =
${union};
`;
}

export { cueNames, GENERATED, renderCueTypes };
