// Turning the game's sound pack into a cue-name union authors can autocomplete. The fetch lives in
// tools/cues.mjs. Read from the pack, never a directory listing: a numbered file family is one cue.

const GENERATED = 'packages/types/cues.generated.d.ts';

/** The pack's own format tag, so a wrong URL fails loudly rather than emptily. */
const FORMAT = 'woc-sfx-runtime-pack';

/** Any total order will do: the sort exists to keep the generated file stable. */
function byCodePoint(a: string, b: string): number {
  if (a === b) {
    return 0;
  }
  if (a < b) {
    return -1;
  }
  return 1;
}

/**
 * Every cue the pack names, sorted and deduplicated. Throws rather than returning empty, since an
 * empty union compiles and silently removes autocomplete.
 */
function cueNames(pack: unknown): string[] {
  if (typeof pack !== 'object' || pack === null) {
    throw new Error('the sound pack is not an object');
  }
  const record = pack as { format?: unknown; clips?: unknown };
  if (record.format !== FORMAT) {
    throw new Error(`expected a ${FORMAT} payload, got format ${String(record.format)}`);
  }
  const { clips } = record;
  if (typeof clips !== 'object' || clips === null) {
    throw new Error('the sound pack has no clips');
  }
  const names = [...new Set(Object.keys(clips))].sort(byCodePoint);
  if (names.length === 0) {
    throw new Error('the sound pack names no cues');
  }
  return names;
}

/** The generated module's text, for a given cue list and where it came from. */
function renderCueTypes(names: readonly string[], source: string): string {
  const union = names.map((name) => `  | '${name}'`).join('\n');
  return `// Generated by tools/cues.mjs from ${source}. Do not hand-edit.
//
// Every sound cue the deployed game ships, which is what \`woc.sound.play\`
// autocompletes. Regenerate with \`pnpm cues\` after a game release adds one.
//
// A cue is not a file: a numbered family such as 'combat_block' is one cue with
// several variants, and playing it picks one the way the game does.

export type KnownCue =
${union};
`;
}

export { cueNames, GENERATED, renderCueTypes };
