// Turning the game's skill-art manifests into a union authors can autocomplete. The fetch lives in
// tools/icons.mjs so a Vitest suite can drive this without a network.
//
// Generated rather than probed: only some abilities ship a `.webp` and the rest are composited on a
// canvas an addon cannot reach, so without the manifest a blank slot cannot tell "no file" from
// "wrong id". LIVE ONLY, because the channels diverge in both directions and a union would
// autocomplete names most players' games have no file for.
//
// The manifest carries no display name, so it cannot map an event's ability name back to an id.

const GENERATED = 'packages/types/icons.generated.d.ts';

/**
 * Every class the game files skill art under, written out because `/ui/skills/` has no index. The
 * `pet` directory is not a class and stays out. A class here whose manifest 404s is a failure.
 */
const ICON_CLASSES = [
  'druid',
  'hunter',
  'mage',
  'paladin',
  'priest',
  'rogue',
  'shaman',
  'warlock',
  'warrior',
] as const;

/** Any total order will do: the sort exists to keep the generated file stable. */
function byCodePoint(a: string, b: string): number {
  if (a === b) {
    return 0;
  }
  if (a < b) {
    return -1;
  }
  return 1;
}

function manifestPath(cls: string): string {
  return `/ui/skills/${cls}/mapping.json`;
}

/**
 * The ability ids one class's manifest names, sorted and deduplicated. Throws rather than answering
 * empty, and checks `class` so a path resolving to the wrong manifest fails.
 */
function iconIds(manifest: unknown, cls: string): string[] {
  if (typeof manifest !== 'object' || manifest === null) {
    throw new Error(`the ${cls} skill manifest is not an object`);
  }
  const record = manifest as { class?: unknown; abilities?: unknown };
  if (record.class !== cls) {
    throw new Error(`the ${cls} manifest says it is for ${String(record.class)}`);
  }
  if (!Array.isArray(record.abilities)) {
    throw new Error(`the ${cls} skill manifest has no abilities array`);
  }
  const ids = record.abilities.map((entry) => {
    const id = (entry as { abilityId?: unknown } | null)?.abilityId;
    if (typeof id !== 'string' || id.length === 0) {
      throw new Error(`the ${cls} skill manifest has an entry with no abilityId`);
    }
    return id;
  });
  const unique = [...new Set(ids)].sort(byCodePoint);
  if (unique.length === 0) {
    throw new Error(`the ${cls} skill manifest names no abilities`);
  }
  return unique;
}

/**
 * The generated module's text: one flat union across classes. Per-class counts are in the header
 * so a drop (art moving) shows on a regenerate diff.
 */
function renderIconTypes(byClass: ReadonlyMap<string, readonly string[]>, source: string): string {
  const all = [...new Set([...byClass.values()].flat())].sort(byCodePoint);
  const classes = [...byClass.keys()].sort(byCodePoint);
  const counts = classes.map((cls) => `//   ${cls}: ${String(byClass.get(cls)?.length ?? 0)}`);
  return `// Generated by tools/icons.mjs from ${source}. Do not hand-edit.
//
// Every ability the deployed game ships a painted icon FILE for, which is what
// \`woc.ui.icon.ability\` can return a URL for. Regenerate with \`pnpm icons\` after a
// game release commits art.
//
// This is not every ability. The game composites an icon on a canvas for anything
// without a file, from a module an addon cannot reach, so an ability outside this union
// has an icon in the game and no icon an addon can point at. That is a gap in what is
// REACHABLE, not a gap in the game.
//
// Read from LIVE, so these are the names most players' games have a file for. A pbe-only
// ability is missing here and still resolves at run time, because the loader reads the
// manifest from the host the player is on and this union is open where it is used.
//
// Ids with a file, per class:
${counts.join('\n')}

export type SkillIconClass =
${classes.map((cls) => `  | '${cls}'`).join('\n')};

export type KnownSkillIcon =
${all.map((id) => `  | '${id}'`).join('\n')};
`;
}

export { byCodePoint, GENERATED, ICON_CLASSES, iconIds, manifestPath, renderIconTypes };
