// Turning the game's item-art manifest into a union authors can autocomplete. The fetch lives in
// tools/items.mjs so a Vitest suite can drive this without a network.
//
// Generated rather than probed, so a blank icon slot means "no file" rather than possibly "wrong
// id". Heroic weapon VARIANTS ship no file and are resolved to their base at run time
// (`ui/kit/item-art.ts`), so they must not be added here.
//
// LIVE ONLY: the channels diverge in both directions, so a union would autocomplete ids most
// players' games 404 on. `iconSize` is the shape check, since there is no `class` field here.

const GENERATED = 'packages/types/items.generated.d.ts';

/** The served square, as a shape check: a payload that is not this manifest fails here. */
const ICON_SIZE = 128;

/** Any total order will do: the sort exists to keep the generated file stable. */
function byCodePoint(a: string, b: string): number {
  if (a === b) {
    return 0;
  }
  if (a < b) {
    return -1;
  }
  return 1;
}

function manifestPath(): string {
  return '/ui/items/mapping.json';
}

/** An array, or an empty one for anything that is not a list. */
function listAt(value: unknown): readonly unknown[] {
  if (Array.isArray(value)) {
    return value;
  }
  return [];
}

/** The values that could name a file, which is what a usable id is here. */
function usableIds(values: readonly unknown[]): string[] {
  return values.filter((id): id is string => typeof id === 'string' && id.length > 0);
}

/** The ids one `entries` array names, skipping an entry it cannot read. */
function idsFromEntries(entries: readonly unknown[]): string[] {
  return usableIds(entries.map((entry) => (entry as { itemId?: unknown } | null)?.itemId));
}

/** The ids every generated batch names, skipping a batch it cannot read. */
function idsFromBatches(batches: readonly unknown[]): string[] {
  return batches.flatMap((batch) =>
    usableIds(listAt((batch as { itemIds?: unknown } | null)?.itemIds)),
  );
}

/**
 * Every item id the manifest names a file for, from both `entries` and `generatedBatches`, sorted
 * and deduplicated. Lenient about one malformed entry, strict about the shape, and throws rather
 * than answering empty, since an empty union compiles and silently removes autocomplete.
 */
function itemIconIds(manifest: unknown): string[] {
  if (typeof manifest !== 'object' || manifest === null) {
    throw new Error('the item manifest is not an object');
  }
  const record = manifest as { iconSize?: unknown; entries?: unknown; generatedBatches?: unknown };
  if (record.iconSize !== ICON_SIZE) {
    throw new Error(`the item manifest says its icons are ${String(record.iconSize)}, not 128`);
  }
  if (!(Array.isArray(record.entries) || Array.isArray(record.generatedBatches))) {
    throw new Error('the item manifest has neither an entries nor a generatedBatches array');
  }
  const named = idsFromEntries(listAt(record.entries));
  const generated = idsFromBatches(listAt(record.generatedBatches));
  const unique = [...new Set([...named, ...generated])].sort(byCodePoint);
  if (unique.length === 0) {
    throw new Error('the item manifest names no items');
  }
  return unique;
}

/** The generated module's text. The count is in the header so a drop shows on a regenerate diff. */
function renderItemTypes(ids: readonly string[], source: string): string {
  return `// Generated by tools/items.mjs from ${source}. Do not hand-edit.
//
// Every item the deployed game ships a painted icon FILE for, which is what
// \`woc.ui.icon.item\` can return a URL for. Regenerate with \`pnpm items\` after a
// game release commits art.
//
// This is not quite every item. What is missing is art the game has not commissioned
// yet, which it enumerates itself rather than leaving silent, plus the heroic weapon
// variants, which ship no file of their own and are drawn from their base weapon's
// painting. \`woc.ui.icon.item\` resolves that second case for you.
//
// Names are NOT here. The manifest carries one per curated entry and it is the ART
// SOURCE name, which drifts from the game's display name on a content rename and is
// gated against nothing. \`ui.icon.itemArtName\` serves it at run time, labelled.
//
// Read from LIVE, so these are the ids most players' games have a file for. An id
// that only pbe ships is missing here and still resolves at run time, because the
// loader reads the manifest from the host the player is on and this union is open
// where it is used.
//
// Ids with a file: ${String(ids.length)}

export type KnownItemIcon =
${ids.map((id) => `  | '${id}'`).join('\n')};
`;
}

export { byCodePoint, GENERATED, ICON_SIZE, itemIconIds, manifestPath, renderItemTypes };
